### ISSUE TITLE
Tests failing on develop

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1814] opened 2017-06-15 16:06 UTC
`TestJournalist2FA.test_totp_reuse_protections` failed on the last Travis [build](https://travis-ci.org/freedomofpress/securedrop/builds/243119371) of develop.

Traceback:

```
=================================== FAILURES ===================================
________________ TestJournalist2FA.test_totp_reuse_protections _________________
self = <tests.test_2fa.TestJournalist2FA testMethod=test_totp_reuse_protections>
    def test_totp_reuse_protections(self):
        """Ensure that logging in twice with the same TOTP token
            fails."""
        resp = self._login_user()
        self.assertRedirects(resp, url_for('index'))
    
        resp = self._login_user()
>       self.assert200(resp)
tests/test_2fa.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/dist-packages/flask_testing/utils.py:329: in assert200
    self.assertStatus(response, 200, message)
/usr/local/lib/python2.7/dist-packages/flask_testing/utils.py:317: in assertStatus
    self.assertEqual(response.status_code, status_code, message)
E   AssertionError: HTTP Status 200 expected but got 302
```

**Comment by garrettr** [comment] 2017-06-15 16:08
@fowlslegs Since you added this test in 37135668d3d7cb49a5cb45f24cdb071877103245, could you take a look at why it's failing?

**Comment by fowlslegs** [comment] 2017-06-15 17:26
I'm not sure why you are getting a `302`. This test has been run over and over again for weeks at this point. The test assertions are correct: you should be getting a `200`. Getting a `302` indicates the second login attempt with the same TOTP token was successful and `Journalist.login()` did not raise a `BadTokenException` as it should have.

**Comment by fowlslegs** [comment] 2017-06-15 17:37
Sorry, still waking up :smile: I see this is on Travis and not locally. Why did that PR get merged if Travis failed? I can't reproduce.

There have been many successful Travis builds since then. I just restarted that one to see if it was a really weird one-off... I don't have any good ideas on this one. Would love to hear if anyone else does.

**Comment by garrettr** [comment] 2017-06-15 17:41
> Why did that PR get merged if Travis failed? I can't reproduce.

@fowlslegs Travis passed for the [PR](https://github.com/freedomofpress/securedrop/pull/1676) that merged this commit, which suggests this is an intermittent error.

Possibly a race condition? Intermittent failures often are. If it's testing the actual TOTP implementation, I think there's a small probability that the following sequence happened:

1. Test fetches TOTP code to use to log in
2. TOTP window rolls over
3. Test tries to log in with now-expired token, fails, surprise redirect to the login page with a flashed error message.

**Comment by fowlslegs** [comment] 2017-06-15 17:44
Oh duh, you're right.

**Closed** 2017-06-15 22:38 UTC
Labels: P-high
