### ISSUE TITLE
Successful submission in de_DE shows stretched icon in the flash message box  

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2657] opened 2017-12-01 22:37 UTC
# Bug

## Description

The successful submission in `de_DE` shows a stretched icon in the message box. 

## Steps to Reproduce

Submit a document in `de_DE` locale.

## Expected Behavior

The green checkbox icon in the flash message should be a proper circle.

## Actual Behavior
![submit_de_de_flash](https://user-images.githubusercontent.com/272303/33506529-36e9cdf4-d716-11e7-9fc6-e5ca1a9ed7b9.png)

**Comment by dachary** [comment] 2017-12-01 22:55
And the flag is too close to the word **Deutsch**, this is not good. I'm not able to reproduce that in a development environment nor in a production environment.

![screenshot from 2017-12-01 23-54-39](https://user-images.githubusercontent.com/433594/33507080-112c5276-d6f3-11e7-8657-890d8139099f.png)

**Comment by kushaldas** [comment] 2017-12-01 23:11
I am seeing the same issue on that address. Only difference is that I am using Google Chrome with Tor in my side. 
![same_here_too](https://user-images.githubusercontent.com/272303/33507510-1763f77a-d71b-11e7-963a-4839db0dd867.png)

**Comment by dachary** [comment] 2017-12-01 23:17
Ah, that's why. There would be work to do for the source and journalist interfaces to work on anything but Firefox.

**Comment by redshiftzero** [comment] 2017-12-01 23:58
Just tested these source interface pages in German and I was also unable to reproduce: looks like both the flag issue and the squished-checkbox issue are likely Chrome-specific rendering issues, so I'm going to close this one.

**Closed by redshiftzero** 2017-12-01 23:59 UTC
Labels: QA: Release
