### ISSUE TITLE
Chinese display off

### ISSUE THREAD

**Issue by bumbleblue** [freedomofpress/securedrop#4084] opened 2019-01-29 12:47 UTC
## Description

Chinese font display is broken; currently using a mix of (equivalent of) serif and sans serif.

## Comments

Recommend using a *heiti* (sans serif) font. Or even better: a universal font like Google's [Noto](https://www.google.com/get/noto/).

Also consider offering traditional and simplified Chinese 🙂

**Comment by heartsucker** [comment] 2019-01-29 12:50
I did a partial annotation here to show the two different fonts in green and black.

![screenshot_2019-01-29_13-46-19](https://user-images.githubusercontent.com/3998464/51909356-b8120500-23cc-11e9-90db-1bfeefc2e7cd.png)

**Comment by heartsucker** [comment] 2019-01-29 12:51
Also as a note, we have simplified Chinese available [here](https://weblate.securedrop.org/projects/securedrop/securedrop/zh_Hans/), but the translations are only 31% done.

**Comment by eloquence** [comment] 2020-12-11 21:30
Can't reproduce the rendering issue flagged by @heartsucker in current release:
![Screen Shot 2020-12-11 at 13 26 27-fullpage](https://user-images.githubusercontent.com/213636/101956457-7f403b00-3bb4-11eb-911f-8105fdf58997.png)

Closing; please reopen if you still see an issue in the above. (CC @ff98sha)

**Closed by eloquence** 2020-12-11 21:30 UTC
Labels: UX, help wanted, i18n
