### ISSUE TITLE
Multiple administrators

### ISSUE THREAD

**Issue by tomlowenthal** [freedomofpress/securedrop#1175] opened 2015-11-04 22:38 UTC
What if SecureDrop needs to have multiple independent administrators? How should that be managed?

**Comment by conorsch** [comment] 2015-12-11 01:44
Right now the Ansible playbook supports multiple admin user accounts, simply by appending to the `ssh_users` variable in `prod-specific.yml`. The value of `ssh_users` can be a string:

```
ssh_users: alice
```

or it can be a YAML list:

```
ssh_users:
  - alice
  - bob
```

In both cases, the Ansible playbook will "do the right thing" and grant admin privileges to both usernames. Specifically, the playbook will:

1. Create the username
2. Add the username to the `sudo` and `ssh` groups
3. Grant passwordless `sudo`

That's all well and good, but it largely assumes that both admins will be working from the same Tails device—not an option if the admins are not geographically collocated. Tasks that the Ansible playbook currently does _not_ support include SSH key management, which should be included in any solution that manages multiple admin accounts.

Regardless of how we improve the coverage of the Ansible tasks, we're still going to have the problem of sharing config state between multiple Tails devices. Since the site-specific values are stored in `prod-specific.yml`, and are not version-controlled beyond the occasional `git stash`, synchronizing that state because quite difficult, and simply must happen out-of-band.

We're looking into migrating away from the painful `prod-specific.yml` workflow anyway, but synchronizing vars state across Tails devices will remain problematic. Git submodules for managing encrypted vars files, anyone?

**Comment by freddymartinez9** [comment] 2016-12-13 16:13
I can tackle the docs on this but a few questions that this issue doesn't seem to address. 

> That's all well and good, but it largely assumes that both admins will be working from the same Tails device

Why does this have to be the case? I assume because they need to have the same THS Auth cookie?  I am also not sure of a use case when you need multiple independent admins with separate SSH access. Anyways feel free to assign it to me.

**Comment by fowlslegs** [comment] 2016-12-13 22:38
>  I am also not sure of a use case when you need multiple independent admins with separate SSH access.

One admin cannot investigate some problem or OSSEC alert, or carry out some necessary upgrade process required to keep their instance up-to-date.

**Comment by freddymartinez9** [comment] 2016-12-16 18:48
Just to be clear @fowlslegs, we would have to have each ssh user to reuse the Onion Service Auth Cookie? So part of the setup is making sure each admin say `alice` and `bob` would have the same Cookie (I _assume_ so, I just want to be explicit) ...

**Comment by fowlslegs** [comment] 2016-12-16 19:30
I just tested and it is possible for each admin to have their own AuthCookie for a given hidden. That way if one admin loses their laptop the other can modify the torrc files and reload tor on the servers to remove their access. Also, just a generally good practice not to share credentials. From `man torrc`:
```
       HiddenServiceAuthorizeClient auth-type client-name,client-name,...
           If configured, the hidden service is accessible for authorized clients only. The auth-type can either
           be 'basic' for a general-purpose authorization protocol or 'stealth' for a less scalable protocol that
           also hides service activity from unauthorized clients. Only clients that are listed here are
           authorized to access the hidden service. Valid client names are 1 to 16 characters long and only use
           characters in A-Za-z0-9+-_ (no spaces). If this option is set, the hidden service is not accessible
           for clients without authorization any more. Generated authorization data can be found in the hostname
           file. Clients need to put this authorization data in their configuration file using HidServAuth.
```

You can see our template in `install_files/ansible-base/roles/tor-hidden-services/templates/torrc`, the relevant bit being:

```
HiddenServiceDir /var/lib/tor/services/ssh
HiddenServicePort 22 127.0.0.1:22
HiddenServiceAuthorizeClient stealth admin
```

You'd probably just want to append `,admin2` to the end of that last line, or perhaps something that would help you remember which `client-name` corresponds to which admin workstation.

It would be nice to eventually provide tools that make this easier, but for orgs that want it now, I think good documentation should be fine.

**Comment by freddymartinez9** [comment] 2016-12-16 20:23
yes but if you go to the torrc/ and `cat hostname` you will get one .onion and one `AuthCookie`. You're talking about adding the ssh user to the `HiddenServiceAuthorizeClient stealth admin,admin2` which is a different thing than I'm describing.

**Comment by freddymartinez9** [comment] 2016-12-16 21:26
I see, maybe I am mis-understanding how Onion Services handle AuthCookies. From the documentation
```
In order to access an ATHS, you need to add one or more "auth-cookie" values
to your Tor configuration file (``torrc``) and restart Tor. Doing this manually
is annoying and error-prone, so SecureDrop includes a set of scripts in
``./tails_files`` that can set up a Tails instance to automatically
configure Tor to access a set of ATHS.
```
I guess I need to poke around the ./tails_files to see how this is done.

**Comment by fowlslegs** [comment] 2016-12-16 21:26
> yes but if you go to the torrc/ and cat hostname you will get one .onion and one AuthCookie.

As in after provisioning on the Ansible Controller? The problem is how `app_display_onions.yml` is written it will only retrieve the first one from `/var/lib/tor/services/ssh/hostname`.

>You're talking about adding the ssh user to the HiddenServiceAuthorizeClient stealth admin,admin2 which is a different thing than I'm describing.

Well you asked:

> Just to be clear @fowlslegs, we would have to have each ssh user to reuse the Onion Service Auth Cookie? 

And that's the question I was responding to.

**Comment by freddymartinez9** [comment] 2016-12-16 21:31
I pushed a small commit here https://github.com/freddymartinez9/securedrop/commit/03d6b297cebc0da2eaeb0143348381fc2e35afca and will work on it some more this weekend once I make sense of the comment I posted above.

**Comment by eloquence** [comment] 2020-09-11 17:15
Since this issue was filed, we added:
- Guidance for managing config updates with multiple admins: https://docs.securedrop.org/en/stable/admin.html#managing-site-specific-updates-on-teams-with-multiple-admins
- Guidance for offboarding admins and rotating keys: https://docs.securedrop.org/en/stable/offboarding.html#rotate-ssh-key

We may still want to add more recommendations to the setup guide or the Admin Guide, but those should be scoped into more specific issues. Closing this one.

**Closed by eloquence** 2020-09-11 17:15 UTC
Labels: docs, feature
