### ISSUE TITLE
Rename `datetimeformat` to prevent collisions with Babel functions

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2374] opened 2017-09-26 18:20 UTC
# Feature request

## Description

Babel injects a function called `datetimeformat` into the jinja environment. We do too, manually. They do not have the same args, and we get `TypeError`s. We should rename our functions to fix this.

## User Stories

As a dev, I don't want to have to track down weird errors if we don't do things in exactly the right order.

**Comment by dachary** [comment] 2017-09-26 20:19
I don't think this is the root of the problem because the error we sometime get is about an argument (relative) which exists in both implementation.

The current fix for this iproblem (with the global journalist/source implemenation) s to ensure the test file reloads the file that journalist/source module. See for instance test_i18n.py 

<pre>
    @classmethod
    def teardown_class(cls):
        reload(journalist)
        reload(source)
</pre>

**Comment by dachary** [comment] 2017-09-26 20:31
I take that back. The [format_dateime](https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L381) provided by default does **not** have a **relative** kwargs argument. So the problem is that the babel module gets reloaded (how ?) and resets the jinja filters. And if the journalist/source is not also reloaded, the implementation is not overloaded.

I suspect changing the name won't help. If the filters are reset we will just get an error because the filter does not exist at all. We need to figure out why the jinja filters are being reset after a test.

**Comment by heartsucker** [comment] 2017-09-27 08:22
Doing a `reoload(journalist)` just resets it the same way. `journalist.app` is called from `journanlst_app.create_app` which calls `i18n.setup_app` and also does the jinja stuff. And this happens in the same order every time. The reason this was a problem was that in the refactor, I changed the order and our function was always being overwritten by the babel one.

**Comment by dachary** [comment] 2017-09-27 08:25
Ah, that makes sense. 👍 on renaming the function to avoid that kind of headache.

**Closed** 2017-10-12 21:09 UTC
Labels: goals: app code cleanup, hackathon
