### ISSUE TITLE
async_genkey: thread safety issue in async_genkey by calling current_app in separate thread.

### ISSUE THREAD

**Issue by tmc** [freedomofpress/securedrop#2609] opened 2017-11-26 04:47 UTC
# Bug
async_genkey calls current_app in some conditions and can raise `RuntimeError: Working outside of application context.`

## Description

async_genkey calls current_app in some conditions and can raise `RuntimeError: Working outside of application context.` Example: https://gist.github.com/tmc/095d490608c7cc5e2aa5f4825cd7a4a3#file-gistfile1-txt-L1122

## Steps to Reproduce

This is a flake I have running tests inside of a container in a qubes 3.2 machine.

## Expected Behavior
To not break in case of an underlying error.

## Actual Behavior
Breaks when trying to call current_app.

## Comments
There's clearly another underlying issue here but it shouldn't blow up in this manner.

**Comment by dachary** [comment] 2017-12-13 17:26
Another instance of this bug with full logs at https://travis-ci.org/freedomofpress/securedrop/builds/315980526?utm_source=github_status&utm_medium=notification

**Comment by dachary** [comment] 2017-12-13 21:18
> This is a flake I have running tests inside of a container in a qubes 3.2 machine.

This always happen when running `make test` on Debian GNU/Linux (no Qubes)

**Comment by dachary** [comment] 2017-12-13 21:43
My theory is that it only happens when running `pytest` with **no argument** because it loads modules that are outside of the tests directory and have side effects. It can reliably be reproduced locally with:

<pre>
make test
</pre>

and never happens with

<pre>
TESTFILES=tests make test
</pre>

Instead of working on actually finding the reason why this happens (although @heartsucker work on refactoring the app helped a lot, there are still place where global side effects on module loading are likely to happen in ways that are difficult to find) let's close this issue in a month or two if it does not show up again.

**Comment by tmc** [comment] 2017-12-14 17:20
@dachary thanks so much for looking into this, that helps illuminate the issue.

**Comment by tmc** [comment] 2017-12-14 17:21
if this can be demonstrated predictably should #2614 be re-opened?

**Comment by dachary** [comment] 2017-12-14 22:00
maybe, if someone is willing to figure out why exactly it happens

**Closed** 2017-12-31 03:34 UTC
Labels: app, bug, goals: sick CI, tests
