### ISSUE TITLE
Improve SecureDrop loading experience over Tor Hidden Services

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1152] opened 2015-10-19 19:21 UTC
In production, all of SecureDrop's web interfaces (the Source Interface and the Document Interface) are only available as Tor Hidden Services, which have extremely restricted bandwidth. In addition, SecureDrop intentionally avoids caching _any_ resources in the client's browser to avoid potential forensic infoleaks.

These qualities combine to make the SecureDrop web interface feel slow and glitchy, particularly when used over an especially slow hidden service connection:

![securedrop source interface performance](https://cloud.githubusercontent.com/assets/407302/10588496/50a10bb8-765b-11e5-8a1c-12f1b1297e1f.gif)
## Specific Issues to Fix
- [ ] Seeing the unstyled page before the CSS loads. This looks glitchy and unprofessional.
- [ ] Seeing the logo resize during the page load
- [ ] Reduce or eliminate the delay in showing the icons (e.g. cloud icon next to "Submit Documents" on the home page)
- [ ] Reduce or eliminate delay on page loads after the first in a session. This requires research, as it conflicts with our current position on avoiding caching web resources, and we would need to make sure that we can use some form of caching without the browser writing the resources to long term storage.
## Potential Resolutions
- Reordering or inlining resources (stylesheets, images)
- Reduce the size of currently used resources to load them faster with the limited bandwidth we have, e.g.
  - Reduce the size of logos
  - Reduce the icons files to just the icons that are actually used in SecureDrop
  - Minify JS and CSS
- Caching

**Comment by garrettr** [comment] 2015-10-19 21:40
I started working on this, but ran into an issue with the development cycle and our existing set of automated development environments. Rather than work around it, I think this is an instructive use case that could help us improve our development environments and automation.

Essentially, the problem is:

1. The `development` environment synchronizes changes to the application code (`securedrop/securedrop`) to the VM, so it automatically synchronizes the type of changes I need to make (changes to HTML templates, CSS, images, JS, etc.). _However_, it does not make the site available via Tor Hidden Service.
2. The `staging` environment _does_ make the site available via Tor Hidden Service, but it installs `securedrop-app-code` from the production apt server. In order to use `staging` to test my changes, I would need to:
    1. Stand up a testing apt server, edit `staging-specific.yml` and associated files to use that instead of the production apt server.
    2. Make changes.
    3. Rebuild the `securedrop-app-code` deb locally, using the `build` vm
    4. Upgrade the testing apt server with the new, testing deb.
    5. Re-run the Ansible playbooks to install the new deb.

    This procedure is manual, complex, and time-consuming.

The `install_local_packages` Ansible role was intended to handle this development workflow use case, but it is currently broken and there has been some work to replace/remove it (#1040).

@conorsch What do you think the best next move is here?

**Comment by conorsch** [comment] 2015-10-19 22:03
@garrettr Ah, a subject near and dear to my heart. The lack of automated building as part of the `staging` environment makes it virtually useless for testing the app code—the `staging` environment is essentially a more convenient `production`, but with more verbose logging and direct SSH access. It's appropriate for testing the deployment process, but not the app code.

The solution is to trigger deb package builds during the staging deployment, and use that artifact during provisioning. I've tabled the `install_local_pkgs` rewrite until I can move many pieces around together. Most of the ansible reorg is finished, but not submitted for review yet, because it's a vicious diff, and would likely require several days of in-person review.

Let me take a look at providing a wrapper playbook with the current state of the ansible config that would essentially chain the build-deb-package-then-provision-staging workflow. That should be shippable with a far less burdensome review process, and provide you with a less hair-pulling process to test bleeding-edge code over Tor.

**Comment by garrettr** [comment] 2015-10-19 22:37
@conorsch The alternative is to make resolving this issue a dependency of the Ansible reorg, which I'm totally fine with. There's a lot of other stuff I could be working on, I just picked this one up since I spent so much time thinking about the issue while filing it and it seemed fairly straightforward.

**Comment by conorsch** [comment] 2015-10-19 23:06
@garrettr Upon closer inspection, there's a more direct path that works with the current config. Try to reproduce and let me know how it treats you.

```
# I say we take off and nuke the entire site from orbit.
# It's the only way to be sure.
vagrant destroy -f build /staging/

SECUREDROP_STAGING_SKIP_TAGS='untagged' vagrant up build /staging/
```
That's it. The build role will run first, and dump out new packages. Then the staging playbook will kick in, and since you've overridden the default of "don't install local packages", the local packages will be used during the staging provisioning run.

The `SECUREDROP_STAGING_SKIP_TAGS='untagged'` is a kludge (it actually only works because of the thorough tagging from #1004), and I suggest we remove the corresponding line from the Vagrantfile all together. Removing it would require that folks spinning up a staging environment also spin up a build VM, but I'm comfortable enforcing that as a development practice.

The current implementation of the `install_local_pkgs` role isn't great, definitely lacks a sufficient dollop of magic sauce, since it still installs the prod packages from the apt repo, then installs the deb packages over top of them, but that problem is better addressed in the overall ansible reorg. The solution described above should get you up and running for comparing development code performance over Tor and local HTTP via port forwarding.

**Comment by conorsch** [comment] 2015-10-19 23:15
Some rough benchmarking info: destroying and recreating `build` and `/staging/` takes about 15 minutes on my machine (i5, 8GB, SSD). Running `
SECUREDROP_STAGING_SKIP_TAGS='untagged' vagrant provision build /staging/` takes only 3 minutes.

**Comment by garrettr** [comment] 2015-10-20 00:00
Tried to reproduce. I got an error:

```
TASK: [install_local_pkgs | if defined copy local deb packages to target system] *** 
fatal: [mon-staging] => input file not found at /Users/garrett/code/freedomofpress/securedrop/install_files/ansible-base/roles/build/ossec-server-2.8.2-amd64.deb or /Users/garrett/code/freedomofpress/securedrop/build/ossec-server-2.8.2-amd64.deb

FATAL: all hosts have already failed -- aborting
```

I will copy the ossec debs (which are built by an Ansible role currently maintained in the separate [ossec repo][]) to `securedrop/build` and try again.

[ossec repo]: https://github.com/freedomofpress/ossec

**Comment by conorsch** [comment] 2015-10-20 20:46
Discussion of the ossec debs is [over in the ossec repo](https://github.com/freedomofpress/ossec/issues/6), with a [proposed solution](https://github.com/freedomofpress/ossec/pull/7) to the clunky error messages.

**Comment by conorsch** [comment] 2015-11-14 02:12
Changes to the `install-local-packages` role tracked in #1040. Have a branch ready to submit that will resolve the rebuilding-on-staging problems described in the comments above.

**Comment by ehartsuyker** [comment] 2016-03-10 15:14
Is using [mod_pagespeed](https://github.com/pagespeed/mod_pagespeed/) an option? I haven't used it yet, but we're considering using the Nginx flavor at work for something.

**Comment by eloquence** [comment] 2020-06-12 00:40
Closing; the behavior described here no longer occurs with current versions of SecureDrop, thanks to improvements that have since been made to templates and styling, and likely also in part due to upstream changes in Firefox ESR.

**Closed by eloquence** 2020-06-12 00:40 UTC
Labels: UX, goals: journalist experience
