### ISSUE TITLE
Bootstrap dev environment with fixed admin credentials

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2968] opened 2018-02-04 08:08 UTC
# Feature request

## Description

The dev env should be booted with fixed admin credentials to make it easier for developers to quickly log in and test features. This means a fixed username, password, and TOTP shared secret.

## User Stories

As a dev, I don't want to have to keep scanning QR codes and memorizing diceware passwords while testing.

**Comment by redshiftzero** [comment] 2018-02-05 20:43
Totally agreed- but this is a dupe of #1662 (slated for 0.6)

**Closed by redshiftzero** 2018-02-05 20:43 UTC
Labels: development env, goals: improve developer workflow
