### ISSUE TITLE
DNS is broken on Focal staging server.

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5655] opened 2020-11-26 10:10 UTC
## Description

`/etc/resolv.conf` contains;

```
nameserver 127.0.0.53
```

## Steps to Reproduce

- [ ] `apt install nmap`

## Expected Behavior

- [ ] `apt` should be able to reach to the servers

## Actual Behavior

- [ ] it is stuck as it can not do any name resolution. 

## Comments

Suggestions to fix, any other relevant information.

**Comment by emkll** [comment] 2020-11-27 20:13
I can reproduce this locally, looks like the default DNS resolver is different in 20.04.

Looking at `/etc/resolv.conf` there is a comment in that file: 
```
# 127.0.0.53 is the systemd-resolved stub resolver
```

The DNS name servers should be configured in `/etc/systemd/resolved.conf`, if the target OS is based on Ubuntu Focal. We should add some conditional logic to handle

We should also add a testinfra test here to ensure we have test coverage.

**Comment by kushaldas** [comment] 2020-11-30 08:52
Okay, the whole trouble is most probably coming from `systemd-resolve` package on Ubuntu Focal.
```
#  ss -pln sport = 53
RTNETLINK answers: Invalid argument
Netid            State              Recv-Q             Send-Q                         Local Address:Port                         Peer Address:Port            Process                                               
udp              UNCONN             0                  0                              127.0.0.53%lo:53                                0.0.0.0:*                users:(("systemd-resolve",pid=582,fd=12))            
tcp              LISTEN             0                  4096                           127.0.0.53%lo:53                                0.0.0.0:*                users:(("systemd-resolve",pid=582,fd=13))
 ```

**Comment by emkll** [comment] 2020-12-09 16:42
closed via https://github.com/freedomofpress/securedrop/pull/5638

**Closed as completed** 2020-12-09 16:45 UTC
Labels: bug
