### ISSUE TITLE
test: Enable xdist

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2755] opened 2017-12-17 11:14 UTC
# Feature request

## Description

Run tests in parallel (using xdist) to speed up the global runtime. 

@tmc has a draft implementation at #2571 

## User Stories

As a SecureDrop contributor I would like tests to be as quick as possible.

**Comment by redshiftzero** [comment] 2017-12-21 16:57
Related: #2535

**Comment by heartsucker** [comment] 2018-01-24 16:28
Note, this depends on #2877 in all likelihood.

**Comment by redshiftzero** [comment] 2019-06-10 22:47
this is a duplicate of #2535, closing

**Closed by redshiftzero** 2019-06-10 22:47 UTC
Labels: feature, goals: sick CI, tests
