### ISSUE TITLE
Add labeling best-practices 

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1141] opened 2015-10-14 19:10 UTC
Labeling is mostly an install-time affair, but the discussion should probably go in `hardware.md` since that's what you look at when purchasing materials. It can be referenced from elsewhere, especially in `install.md`.

**Comment by conorsch** [comment] 2016-05-12 00:31
Closing as dupe of #1120, which is resolved.

**Comment by flamsmark** [comment] 2016-05-13 22:50
I still think there should be some mention of labeling in the hardware doc because that's where purchases get planned. It's definitely better for the admin if they have misc supplies like labels available before they start the install.

**Comment by conorsch** [comment] 2016-05-13 22:53
Fair point, a more itemized approach during the planning phase would be helpful for setting expectations. Right now the Hardware doc falls short:

```
$ grep -i label docs/hardware.rst 
you should consider how you will label or identify them and buy drives
accordingly. Drives that are physically larger are often easier to label
(e.g. with tape or a label from a labelmaker).
```

Let's add labels as first-class item to be procured as part of the physical install.

**Comment by freddymartinez9** [comment] 2016-12-13 16:14
@conorsch you can also assign this one to me. I had the same concerns as @flamsmark while setting up an SD and meant to open this issue myself.

**Comment by redshiftzero** [comment] 2016-12-13 20:28
Turns out [we can only people to issues if they 1) are the person that made the issue or 2) they have push access to the repo](https://github.com/isaacs/github/issues/100), but consider yourself assigned!

**Comment by fowlslegs** [comment] 2016-12-13 22:39
We just need a Freddy label :stuck_out_tongue_winking_eye:

**Comment by huertanix** [comment] 2017-05-04 17:01
Hey everyone, I'm working on SecureDrop stickers that the FPF crue can bring to installs to label stuff (or maybe print themselves)? and also make sure no one confuses one thing for another. Here's a sample sheet of what I've designed so far if anyone has any thotz:
![sd sticker pack](https://cloud.githubusercontent.com/assets/72914/25715518/b806ef14-30c9-11e7-9e6e-319708ef0da1.png)

**Comment by garrettr** [comment] 2017-05-26 23:07
I can quickly add a section to the **Hardware** documentation that encourages the purchase of labeling supplies, as @flamsmark requested.

**Comment by garrettr** [comment] 2017-05-26 23:09
@huertanix Those custom labels look great! Do you think it will be easy for administrators to purchase them, or make their own? I expect that it's most feasible to order a limited run of laminated sticky labels, which we could provide to instances that we help with setup, but that it wouldn't be easy/cost-effective to somehow make them readily available to any organization via online ordering.

**Closed** 2017-05-30 16:25 UTC
Labels: docs, Pending PR
