### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by chemagallego** [freedomofpress/securedrop#1166] opened 2015-11-01 09:41 UTC
Next links are broken: Error 404

https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md

https://github.com/freedomofpress/securedrop/blob/develop/docs/source_user_manual.md

https://github.com/freedomofpress/securedrop/blob/develop/docs/journalist_user_manual.md

https://github.com/freedomofpress/securedrop/blob/develop/docs/develop.md

**Comment by ageis** [comment] 2015-11-01 13:51
This is because we converted our docs from Markdown to reStructuredText for [ReadTheDocs](https://docs.securedrop.org) in #1158.

**Comment by garrettr** [comment] 2015-11-02 01:57
@ageis While the ReadTheDocs migration was the cause of the broken links, that does not mean the issue can just be closed.

@chemagallego Where are you getting the broken links from? Are they on securedrop.org or another website? From your browser bookmarks? Somewhere else?

**Comment by chemagallego** [comment] 2015-11-02 10:34
1) Yesterday was broken but now It seems to work properly once again at https://securedrop.org/faq#media_orgs

![2](https://cloud.githubusercontent.com/assets/6845281/10879417/10ed2124-8154-11e5-8034-f645645e5310.PNG)

2) At https://github.com/freedomofpress/securedrop it fails now (Error 404) in the four links I show you below.

![1](https://cloud.githubusercontent.com/assets/6845281/10879455/6292acf6-8154-11e5-93cc-ba807db304f5.PNG)

Example...

![3](https://cloud.githubusercontent.com/assets/6845281/10879573/fcf532d2-8154-11e5-90d0-23ca6f81076c.PNG)

3) I'm not using bookmarks, just searching using any search engine.

**Comment by garrettr** [comment] 2015-11-02 14:24
@chemagallego Thanks for the detailed response! From it, I can see multiple issues that we need to address:

- [x] Links on securedrop.org, which appear to have since been fixed, as you said in your comment
- [ ] Links in the README. I am fixing them now.
- [ ] Search engine results. This is harder to fix, and I am not sure what the best approach is.

**Comment by ageis** [comment] 2015-11-02 17:16
Google actually has a tool for removing outdated links, I can cover that:

![removal](https://cloud.githubusercontent.com/assets/1161532/10888642/41beec22-8142-11e5-8eda-3adc7fc6b532.png)

**Comment by conorsch** [comment] 2015-11-02 17:59
Removing the outdated links from search indexes is a good idea. We should also consider adding placeholders for the most commonly used documents, since there are a lot of URLs circulating out there for `install.md` and `hardware.md`. A simple markdown document pointing to the new docs.securedrop.org and explaining the docs migration should suffice.

**Comment by garrettr** [comment] 2015-11-02 22:54
For future reference, please shares links to the docs from https://docs.securedrop.org instead of direct links to the underlying Read the Docs subdomain (https://securedrop.readthedocs.org). That will future-proof the URLs (since we can control redirects on `*.securedrop.org`) so don't have the same situation happen again if we decide to move away from building/hosting docs with Read the Docs.

**Comment by garrettr** [comment] 2015-11-04 20:10
Looks like Google's "remove outdated links" tool worked, I just did a few searches for queries like "install securedrop" and "securedrop hardware" and saw links to the new documentation, instead of links to the old Markdown files on Github.

**Comment by garrettr** [comment] 2015-11-04 21:16
We've completed the checklist from https://github.com/freedomofpress/securedrop/issues/1166#issuecomment-153030165, and I added placeholders as suggested in https://github.com/freedomofpress/securedrop/issues/1166#issuecomment-153101441 in #1174. Closing.

**Closed by garrettr** 2015-11-04 21:16 UTC

**Comment by chemagallego** [comment] 2015-11-05 08:50
Hi,

It was just a question of time to allow DNS propagation. It also works for me.

Thanks
