### ISSUE TITLE
Vagrant syntax and behavior broken with 1.8.1

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1304] opened 2016-05-19 22:25 UTC
Now to start and provision either the prod or staging VMs one must run

`vagrant up {app,mon}-staging --no-provision && vagrant provision {app,mon}-staging`

instead of simply

`vagrant up /staging$/`.

This is a regression in both syntax (our regular expression `/staging$/` doesn't work) and behavior (when multiple VM names are passed to `vagrant up` it will bring up and then provision them one at a time, causing failure because some tasks require both the app and mon server to be up). I think @conorsch has been tracking this better and knows the situation upstream. Care to chime in on that/ share relevant links? Do we change this in the dev docs for now and then revert or is it something that will be fixed very shortly and is not worth bothering ourselves over?

**Comment by conorsch** [comment] 2016-05-19 22:32
Dupe of #1241.

**Comment by conorsch** [comment] 2016-05-19 22:33
>  Do we change this in the dev docs for now and then revert or is it something that will be fixed very shortly and is not worth bothering ourselves over?

My vote would be to change the dev docs and provide the more explicit version. Let's move conversation to #1241, though, since there are external links there that help contextualize the discussion a bit.

**Closed by conorsch** 2016-05-19 22:33 UTC
