### ISSUE TITLE
config.py will break in next release becuase of changed wordlist

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1328] opened 2016-06-11 16:47 UTC
Because `config.py` is in the `.gitignore`, during the release where the new wordlist is pushed out, old systems will break because the wordlist has moved. Currently people's dev environment will be "broken" out of the box.

Solutions:
1. Move the wordlist back to its old location
2. Force push the single line change and mention the possibility merge conflicts in the release notes
3. Include this manual step in the next set of release notes

I think Option 2 makes the most sense.

**Comment by garrettr** [comment] 2016-06-13 19:37
Good catch! I totally forgot we allow that to be configured in `config.py` (which is really unnecessary, and should probably be removed in a future release).

Any resolution that brings with it the possibility of breakage for admins (e.g. option 2, which could cause merge conflicts) should be avoided unless absolutely necessary, because it has the potential to create a support burden for us at FPF.

On the other hand, these changes are in develop and therefore targeted for 0.4, which has so many other changes that it will probably not be possible to provide an auto-upgrade due to the limitations of SecureDrop's current architecture. Therefore, it will require a manual "migration" process, which provides an opportunity for issues like this to be address through an automated migration script.

**Comment by garrettr** [comment] 2016-06-13 19:38
> Currently people's dev environment will be "broken" out of the box.

Why is this so? New virtual environments run the Ansible playbooks, which derive `config.py` from `config.py.example`, which was updated to point to the new location of the wordlist in #1276.

**Comment by garrettr** [comment] 2016-06-13 20:06
> Why is this so?

I reproduced the issue. This only affects the development environment because it uses Vagrant shared folders and thus retains all files under the `securedrop` repo root across VM destroy/create cycles. The other development environments (staging, prod) do not use shared folders and so will not be affected.

**Comment by garrettr** [comment] 2016-06-13 20:09
The problem is the `Copy starter config.py template if missing.` task in `roles/app/tasks/initialize_securedrop_app.yml`, which only generates `config.py` from `config.py.example` if it does not already exist.

This behavior ***should not*** be changed. If it were, re-running the playbooks on a production environment would:

1. Overwrite the existing `config.py` with `config.py.example`
2. Inject some values from `prod-specific.yml` (this is not a problem)
3. Re-generate some randomly generated values. This *would be a problem*, specifically:
 * Regenerating `SECRET_KEY` for the Source Interface and Document Interface would invalidate all currently active sessions, forcing all sources and journalists to log in again. This is not a serious problem, and could be considered acceptable.
 * Regenerating the `SCRYPT_ID_PEPPER` and `SCRYPT_GPG_PEPPER` would invalidate all currently existing source accounts, permanently preventing them from being able to log in or check their replies. This is a serious problem and should be avoided.

**Comment by garrettr** [comment] 2016-06-13 20:11
Given all that I've just said, my inclination is to go with solution 1, and move the wordlist back to its original location for now. That will fix the issue with a minimum of effort in the short term. What do you think, @heartsucker?

In the long term, SecureDrop's "configuration persistence, update and migration" story is a mess and should be fixed in a holistic manner.

**Closed** 2016-06-20 22:08 UTC
