### ISSUE TITLE
Double submission of journalist replies

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1392] opened 2016-08-26 07:11 UTC
I can't reproduce this, but when replying to a source, clicking the submit button sent two replies. When returning to the conversation page, there were two flash messages saying that my reply was went and two entries for my reply in the list. I confirmed that the `db.sqlite` has two entries.

**Comment by fowlslegs** [comment] 2017-03-09 22:00
Going to close this one since we haven't seen it in 7 months. Re-open please if you can ever reproduce or it crops up for anyone else who sees this.

**Closed by fowlslegs** 2017-03-09 22:00 UTC
Labels: bug, unable to reproduce
