### ISSUE TITLE
Ansible fails in common on grsec_lock

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#760] opened 2014-11-22 02:02 UTC
Running OSX Yosemite (10.10.1), with VirtualBox, vagrant and Ansible fully up-to-date. Trying to run `vagrant up /staging$/` here is where the playbook fails (some context provided):

````
TASK: [common | waiting for server to come back] ****************************** 
ok: [mon-staging -> 127.0.0.1] => {"changed": false, "elapsed": 20, "path": null, "port": 2222, "search_regex": null, "state": "started"}
ok: [app-staging -> 127.0.0.1] => {"changed": false, "elapsed": 20, "path": null, "port": 2200, "search_regex": null, "state": "started"}

TASK: [common | stat path="/proc/sys/kernel/grsecurity/grsec_lock"] *********** 
fatal: [app-staging] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
fatal: [mon-staging] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/kevin/securedrop-staging.retry

app-staging                : ok=25   changed=20   unreachable=1    failed=0   
mon-staging                : ok=25   changed=20   unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
````

**Comment by garrettr** [comment] 2015-03-27 01:06
@ageis Is this still an issue?

**Comment by ageis** [comment] 2015-03-27 01:11
I switched away from OSX when I got my new laptop so I haven't seen the issue again. I assume you haven't reproduced either, but I will test soon to make sure.

**Comment by ageis** [comment] 2015-03-31 16:26
Still have this issue on that machine, now failing on the earlier reboot and "waiting for server" task. Tried everything I could to get past it - assigning highest priority to vagrant and VBox and closing everything else, adjusted the timeouts and async values to far greater than should be necessary, even increased the memory and CPUs allotted to each VM. All to no avail. I attribute this to something about the machine, which has been very slow on virtualization ever since the upgrade to Yosemite (why I have no idea - it has VT-x, I/O APIC enabled, and simple benchmarks don't hint at any issues). I would say the VMs just take way too long to reboot which is why we have the failure on this specific task, but even a wait/async value of 10 minutes was not enough here. I think something's just very wrong with this computer and it can't perform well enough to run the playbooks, so I'd be fine with closing the issue unless/until we can get a second corroborating report.

**Comment by conorsch** [comment] 2015-04-21 23:39
Can't reproduce locally, and we haven't gotten any new reports indicating that this problem shows up on different hardware, so I'm closing this issue.

**Closed by conorsch** 2015-04-21 23:39 UTC
Labels: bug
