### ISSUE TITLE
All links are broken in https://securedrop.org/faq#audits

### ISSUE THREAD

**Issue by jdcc** [freedomofpress/securedrop#1568] opened 2017-02-08 17:23 UTC
I was trying to look through the audit info, but all the links in that section appear to be broken.

e.g. https://freedom.press/securedrop-files/iSEC_OTF_FPF_SecureDrop_Deliverable_v1.2.pdf returns a 404.

**Comment by conorsch** [comment] 2017-02-08 18:04
Drat, thanks for reporting this, @jdcc. This was caused by a recent website migration, and we didn't update the URLs for the audit PDFs. Will get that cleaned up shortly.

**Comment by conorsch** [comment] 2017-02-08 18:48
All links to the the audit PDFs are now fixed: https://securedrop.org/faq Again, thanks for bringing this to our attention, @jdcc.

**Closed by conorsch** 2017-02-08 18:48 UTC

**Comment by jdcc** [comment] 2017-02-08 19:56
No problem! Happy to be another set of eyes.
