### ISSUE TITLE
Recommended hardware will likely brick itself on first boot

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1244] opened 2016-02-02 19:18 UTC
The Intel NUC D54250WYK has a BIOS issue that will cause the unit to brick themselves if they attempt to suspend. Which I found out the hard way by bricking the two servers I just bought.

https://communities.intel.com/thread/76708?start=0&tstart=0
https://communities.intel.com/message/359708#359708

Can someone add this to the documentation? (I might do it later when I'm not busy dis/re-assembling these)

**Comment by conorsch** [comment] 2016-02-02 19:22
@ehartsuyker Ouch, thanks for the report. Were you intentionally suspending the servers, or did they reach sleep state accidentally, for example due to a power button bump? We'll certainly add mention of this to the docs, but more background on your situation may prove be useful for making recommendations for first-time admins.

**Comment by ehartsuyker** [comment] 2016-02-02 19:27
This happened because I pushed the power button to power down, and the (complete lack of a) manual that comes with it does not specify that the power button causes them to enter suspend as opposed to powering off. However, from what forums are saying this can happen a number of ways. One user said he averaged something like only 6 days of uptime between brickings.

**Comment by garrettr** [comment] 2016-03-08 00:58
Holy crap, this is a terrible issue! Thanks for bringing it to our attention, @ehartsuyker. I've done a lot of messing around/rebooting by pressing the power button on NUCs, and never encountered something like this - maybe it's only an issue on newer models? Were you able to reset the BIOS to recover the devices, as described in some of the links you provided?

**Comment by conorsch** [comment] 2016-03-08 01:00
I count myself very lucky never to have experienced this one myself. Based on the documentation @ehartsuyker provided, though, it's definitely something we should document (and #1254 includes docs updates).

**Comment by ehartsuyker** [comment] 2016-03-08 07:30
@garrettr Yes, I was able to open them and reset the BIOS by unplugging the battery, so this is more a bricking where they won't power on, and not a brick that completely ruins the motherboard. I also updated the BIOS and have adopted the strategy of "hold the power button until it is definitely off." I haven't have the issue again, but I'm also probably not going to attempt to reproduce it. :)

**Comment by conorsch** [comment] 2016-05-11 23:56
Resolved via #1254.

**Closed by conorsch** 2016-05-11 23:56 UTC
