### ISSUE TITLE
Add option in installation to not enable ssh access

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#297] opened 2014-01-29 03:39 UTC
Some organizations do not want their admins having remote access to the app and monitor server and would like to disable all ssh access. This installation option would be for organizations that have 24/7 on site support or are willing to accept that admin(s) would need to be physically present to access the app and monitor server.

**Comment by garrettr** [comment] 2015-03-25 23:48
@dolanjs Do we still want to implement this? Should be fairly straightforward now that we're using Ansible. If we do decide to add this feature, it will be important to have documentation for it.

**Comment by dolanjs** [comment] 2015-03-26 00:37
It has been requested by one org. The idea behind it is that they didn't want their IT staff to have remote access and since their IT staff didn't have physical access the journalist would need to be involved in allowing the admin access to the console. Think that other orgs may want this and it should be relatively easy to implement in ansible

**Comment by msheiny** [comment] 2017-09-28 13:10
Yep I've had another organization request this feature. I'm all for bumping priority of it.

**Comment by redshiftzero** [comment] 2018-02-20 23:29
Duplicate of #2091

**Closed by redshiftzero** 2018-02-20 23:29 UTC
Labels: ops/deployment
