### ISSUE TITLE
avoid extra reboots

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#951] opened 2015-03-26 18:14 UTC
Currently in the develop version, under certain situations, the playbook will cause 2 reboots in the common role. 1 during installing the grsec kernel and 1 during the cron-apt task to perform system upgrades. We should either reorganize the order of these tasks or change the reboot tasks to an ansible handler to avoid the extra reboot.

**Comment by conorsch** [comment] 2015-12-10 01:25
Responding to the original spirit of this issue, I don't much object to a dual reboot in the playbook, particularly when the order is:

1. Reboot if security updates were just installed
2. Reboot if a grsecurity-patched Linux kernel was just installed

When bootstrapping a system, it makes sense to update everything to a predictable baseline and then start specialized configuration tasks, such as setting up SecureDrop. Therefore I suggest we allow two reboots during the initial installation.

_However_, I recently noticed that in some cases there could be _three_ reboots during a fresh install, since the grsecurity role doesn't handle checking for the kernel version intelligently. That's due to a regression introduced in #1196, and is easily fixed with a second include of the `check_installation.yml` task list, to refresh the value of `running_grsec`.

**Comment by conorsch** [comment] 2017-03-14 19:55
This is not a priority to refactor, certainly not for the 0.4 release. We have sane rebooting logic as part of the external grsecurity install role (https://github.com/freedomofpress/ansible-role-grsecurity), and we'd do well to incorporate that logic into this repo for configuring SecureDrop, rather than duplicating the logic.

**Comment by conorsch** [comment] 2017-05-10 23:06
Tackling this issue. Pulled it onto the 0.4 milestone because we're seeing inconsistent reboot behavior between local Vagrant VMs and the EC2 CI setup (#1666). We need to make sure reboots work consistently and reliably in all environments, most especially hardware.

The reason why reboot behavior is working in some locations but not in others involves how Ansible handles the combination of `local_action` and `wait_for`, particularly how hostvars such as `ansible_host` are resolved (e.g. `ansible_host` becomes `localhost` in a wait_for action delegated to localhost). The safest way to reliably side-step this problem to take a two-step approach where a separate task registers the desired hostname target to be waited for in a uniquely named fact, then references that uniquely named fact in the subsequent wait_for task.

Additionally we should write a single implementation of reboot-and-wait-for, then include that where necessary to keep the config DRY and predictable.

**Closed** 2017-05-23 14:07 UTC
Labels: ops, Pending PR
