### ISSUE TITLE
Pfsense null configuration XML tag format has changed

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2282] opened 2017-09-11 22:28 UTC
## Description 

It looks like there have been some changes to the XML null configuration tag format used by pfSense, now requiring `<tag></tag>` instead of the `<tag/>` format currently used in the templates that SecureDrop is shipping. 

Upstream issue: https://redmine.pfsense.org/issues/6893

## Steps to Reproduce

1. Download firewall templates.
2. Attempt to load.

## Expected Behavior

Template loads obviating the need for manual config.

## Actual Behavior

The template does not load. 

## Comments

This necessitates the templates to be regenerated using the (latest) updated format. 

Given the tight timeline until 0.4.3 is released, I suggest that we push the resolution of this into 0.4.4 to give sufficient time to generate and test the updated firewall templates. In the meantime, people installing SecureDrop will need to fall back to the manual configuration, and the documentation should indicate that manual configuration is necessary to avoid frustration in current users. 

@freddymartinez9 discovered this while testing #2281 on hardware.

**Comment by freddymartinez9** [comment] 2017-09-12 16:50
I realized yesterday that I am in the middle of a fresh install with the latest pfSense. When I have a SD install complete with a clean (factory reset device pfSense) I can do an export of their configurations, so we won't have to manually fix these tags.

**Comment by freddymartinez9** [comment] 2017-09-13 21:24
pushed this commit https://github.com/freedomofpress/securedrop/commit/ac4ce01382bd23a156140ba1d3700f7171292a77 but it requires a fresh pfSense firewall reset.  I will try to test this week

**Comment by freddymartinez9** [comment] 2017-09-14 22:59
I tested my commit https://github.com/freedomofpress/securedrop/commit/ac4ce01382bd23a156140ba1d3700f7171292a77 just now using a working SecureDrop install. Here is what I did:
 1) Manually install SecureDrop and the firewall
 2) Factory reset the pfSense firewall router
 3) Using the clearnet web browser (Unsafe browser) I went to my branch and downloaded the `.xml` files as "raw" from GitHub (**note**: this won't work using Tor due to the `clearnet` user chroot in Tails).
 4) Confirmed the factory reset was successful, no firewall rules were in the pfSense admin GUI. Also the admin user's password is reset. 
  5)  Follow the steps in our [docs](https://docs.securedrop.org/en/stable/network_firewall.html) up to "SecureDrop Configuration"
 6) Restore the `xml` files for each section.
 7) Reboot the firewall (important step)
 8) Test connectivity to the `.onion` using both Tor Browser and ssh.

I will test further using a fresh SD install next week.

**Comment by redshiftzero** [comment] 2017-10-12 16:53
Moved this to 0.4.5 as there is a pending PR (#2317) that is unlikely to be merged in time for the 0.4.4 release

**Comment by eloquence** [comment] 2020-09-18 18:21
This was resolved in #3099.

**Closed by eloquence** 2020-09-18 18:21 UTC
Labels: bug
