### ISSUE TITLE
multi-admin behavior: no error at missing v3_onion_services value in an installed system

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#4778] opened 2019-09-10 11:28 UTC
## Description

A short summary of the issue.

## Steps to Reproduce

- [ ] Backup your v2 only site-specific file before upgrade
- [ ] Test multi-admin behavior. Conduct this test step after v3 is enabled on the server:
  - [ ] Back up `site-specific`, and copy the version from before the upgrade into place instead. Re-run `./securedrop-admin install`, and verify that it fails with a user-friendly message, due to `v3_onion_services=False`.

## Expected Behavior

Seeing an user-friendly error message

## Actual Behavior

Can not see any error message.

**Comment by zenmonkeykstop** [comment] 2019-09-10 16:17
Confirmed for me.

**Comment by rmol** [comment] 2019-09-11 16:19
I'm seeing the same error. I think this is working as expected.

**Comment by rmol** [comment] 2019-09-11 16:29
What should an admin do if they actually intend to stop offering v3 services, though?  Do we really want to disallow that, or at least to require manual (error-prone) intervention? If not, we shouldn't break `securedrop-admin install` after a legitimate `sdconfig` change. :thinking:

**Comment by zenmonkeykstop** [comment] 2019-09-11 16:55
That's worth breaking out into an issue IMO.

**Comment by zenmonkeykstop** [comment] 2019-09-11 16:58
But also IMO since v3 services will be *required* eventually, and there's a migration path that allows for both v2 and v3 for a smooth transition, my hope would be that admins would follow that one rather than switching from v2 to v3 and then back again if they hit problems
.

**Comment by conorsch** [comment] 2019-09-11 16:59
Agreed with @zenmonkeykstop: v2 onions won't be around forever. If an Admin really wants to downgrade from v3 -> v2, that's entirely possible with some small tweaks manually to the torrc file. Supporting that regressive change as a first-class feature of the sdconfig workflow seems like more work than it's worth.

**Comment by eloquence** [comment] 2019-09-18 21:35
As discussed, this was clarified in the docs:

> In a future release of SecureDrop, v3 onion services will be required rather than optional, and there is no automatic downgrade path from v3 to v2 using the securedrop-admin tool.

Closing this issue as a result.

**Closed by eloquence** 2019-09-18 21:35 UTC
Labels: QA: Release
