### ISSUE TITLE
CI Lint check failing because `check-desktop-files` always fails in CircleCI.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#7007] opened 2023-10-16 14:09 UTC
## Description

The `check-desktop-files` Makefile target always exits with an error in CircleCI, even if there are no pending desktop file changes. It does not fail locally.

## Steps to Reproduce

See eg https://app.circleci.com/pipelines/github/freedomofpress/securedrop/6477/workflows/84575a30-c7fc-47d0-87bf-315b62e5a38e/jobs/73111

## Expected Behavior

- the target passes

## Actual Behavior

- the target fails with an error `Desktop files are out of date. Please run \"make update-desktop-files\" and commit the changes.`

## Comments

Suggestions to fix, any other relevant information.

**Comment by cfm** [comment] 2023-10-16 19:15
CI is correct, since #6984 was merged without running `make update-desktop-files`.  Maybe this is a reason to reconsider #6997 and rather have Weblate's pull requests fail `lint` *until* their desktop files have been updated.  For now, the mystery is why it *isn't* failing (producing a diff) locally.

```sh-session
(.venv) circleci@ip-10-0-83-117:~/project$ make check-desktop-files
make[2]: Nothing to be done for 'install_files/ansible-base/roles/tails-config/templates/ssh_config.j2'.
Desktop files are out of date. Please run "make update-desktop-files" and commit the changes.
make: *** [Makefile:386: check-desktop-files] Error 1
(.venv) circleci@ip-10-0-83-117:~/project$ git diff
diff --git a/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2 b/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
index 3a9c2837b..184779524 100644
--- a/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
+++ b/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
@@ -28,5 +28,12 @@ Name[tr]=SecureDrop Gazeteci Arayüzü
 Name[zh_Hans]=SecureDrop 记者界面
 Name[zh_Hant]=SecureDrop 記者使用介面
 Name=SecureDrop Journalist Interface
+Icon[ca]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[cs]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[is]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[sk]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[sv]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[tr]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[zh_Hans]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
 Icon={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
 Exec=/usr/local/bin/tor-browser {{ item.0.onion_url }}
diff --git a/install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2 b/install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
index 50efd29c2..354d395c6 100644
--- a/install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
+++ b/install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
@@ -28,5 +28,12 @@ Name[tr]=SecureDrop Kaynak Arayüzü
 Name[zh_Hans]=SecureDrop 线人界面
 Name[zh_Hant]=SecureDrop 線人使用介面
 Name=SecureDrop Source Interface
+Icon[ca]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[cs]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[is]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[sk]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[sv]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[tr]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[zh_Hans]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
 Icon={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
 Exec=/usr/local/bin/tor-browser {{ item.0.onion_url }}
```

**Comment by cfm** [comment] 2023-10-16 19:19
This is reproducible as a discrepancy between the development virtual environment and the development container:

```sh-session
(.venv) user@sd-dev:~/securedrop$ git reset --hard && make check-desktop-files
HEAD is now at b9a8d5f3f Merge pull request #6984 from weblate-fpf/weblate-securedrop-securedrop
make[2]: Nothing to be done for 'install_files/ansible-base/roles/tails-config/templates/ssh_config.j2'.
(.venv) user@sd-dev:~/securedrop$ git reset --hard && securedrop/bin/dev-shell make -C .. check-desktop-files
HEAD is now at b9a8d5f3f Merge pull request #6984 from weblate-fpf/weblate-securedrop-securedrop
[...]
make: Entering directory '/home/user/securedrop'
make[2]: Nothing to be done for 'install_files/ansible-base/roles/tails-config/templates/ssh_config.j2'.
Desktop files are out of date. Please run "make update-desktop-files" and commit the changes.
make: *** [Makefile:386: check-desktop-files] Error 1
make: Leaving directory '/home/user/securedrop'
```

**Comment by cfm** [comment] 2023-10-16 19:55
...and further as a difference in `msgfmt` versions:

```sh-session
user@sd-dev:~/securedrop$ msgfmt --version && msgfmt        -d install_files/ansible-base/roles/tails-config/templates/locale       --desktop       --template install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2.in        --output-file install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2 && git diff
msgfmt (GNU gettext-tools) 0.21
Copyright (C) 1995-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

```sh-session
user@ee178d080da1:/home/user/securedrop$ msgfmt --version && msgfmt        -d install_files/ansible-base/roles/tails-config/templates/locale       --desktop       --template install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2.in        --output-file install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2 && git diff
msgfmt (GNU gettext-tools) 0.19.8.1
Copyright (C) 1995-1998, 2000-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
diff --git a/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2 b/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
index 3a9c2837b..184779524 100644
--- a/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
+++ b/install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
@@ -28,5 +28,12 @@ Name[tr]=SecureDrop Gazeteci Arayüzü
 Name[zh_Hans]=SecureDrop 记者界面
 Name[zh_Hant]=SecureDrop 記者使用介面
 Name=SecureDrop Journalist Interface
+Icon[ca]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[cs]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[is]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[sk]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[sv]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[tr]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
+Icon[zh_Hans]={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
 Icon={{ tails_config_securedrop_dotfiles }}/securedrop_icon.png
 Exec=/usr/local/bin/tor-browser {{ item.0.onion_url }}
```

**Comment by cfm** [comment] 2023-10-16 20:11
See autotools-mirror/gettext@1c9b7215050412f75b3cb6348aaec13206c7ad20 for the relevant change in default behavior between Ubuntu Focal's gettext 0.19.8.1 and Debian bullseye's gettext 0.21.  We can still get the behavior we want from both versions, without changing what's installed anywhere.  Fix forthcoming in your `test-strings-lint` branch, @zenmonkeykstop.

**Comment by legoktm** [comment] 2023-10-16 20:38
Oof, it seems like you have a workaround, otherwise we can do a hack like the run-mypy script and always run it inside the dev container.

**Comment by legoktm** [comment] 2023-10-16 22:27
> CI is correct, since #6984 was merged without running `make update-desktop-files`. Maybe this is a reason to reconsider #6997 and rather have Weblate's pull requests fail `lint` _until_ their desktop files have been updated.

So does this mean after every Weblate merge CI will fail until someone manually runs update-desktop-files? In that case I agree we should have that be part of the Weblate PR merge.

**Comment by cfm** [comment] 2023-10-16 22:31
Every Weblate pull request *with changes in `securedrop/desktop`* needs `make update-desktop-files`, either pre- or post-merge.  (These are rare.)  I'd planned to do the latter as part of reviewing translations for this release, but @zenmonkeykstop beat me to it...well, continuously. :-)

If you do favor the former, I think we can document that straightforwardly in `make check-desktop-files` on pull requests inbound from Weblate.

**Comment by legoktm** [comment] 2023-10-16 22:42
Yeah, I think doing it pre-merge would be best, that way we can keep CI in a always-passing state on develop as much as possible. And since it's rare it shouldn't require manual work that often, hopefully.

(n.b. we could also have github-actions push a commit if it detects a specific file is changed so it really is automated, but that's for another time...)

**Closed as completed** 2023-10-16 23:41 UTC
Labels: QA: Release
