### ISSUE TITLE
Switch from Ubuntu Server 12.04 to Tails Server

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#46] opened 2013-10-08 18:12 UTC
We can't do this any time soon because Tails Server isn't released yet, but here's the blueprint: https://tails.boum.org/blueprint/server_edition/

When there's a stable version released keeping the servers secure will be way simpler if we make the source server, document server, and monitor server all use Tails instead of Ubuntu.

**Comment by garrettr** [comment] 2015-03-25 21:21
@micahflee As far as I can tell, no progress has been made on "Tails Server" since this issue was created. In the meantime, we have invested considerable effort into provisioning secure servers, which I would argue are actually *more* secure than what is proposed in that document (they have monitoring via OSSEC, hardened kernels via grsecurity by default, etc.).

At this point, I actually think we're in a position to develop *our own* "server edition" based on the Ansible playbooks we've already developed for SecureDrop 0.3. In fact, it might make sense for us to split that out of the SecureDrop repo and it as a separate project for a "hardened server base".

**Comment by garrettr** [comment] 2015-03-25 21:23
I asked in the Tails IRC, and one of the core devs confirmed that "Tails Server Edition" is no longer an active project.

> garrettr_: Is "Tails Server Edition" (https://tails.boum.org/blueprint/server_edition/) an active project?
> BitingBird: garrettr_: not really

As a result, I am going to close this issue, since it is specifically about "Tails Server". I do think we should consider developing our own "server edition" as its own open-source project apart from SecureDrop.

**Closed by garrettr** 2015-03-25 21:23 UTC
