### ISSUE TITLE
Tails desktop shortcuts for Source and Journalist interface require reboot on first install

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2678] opened 2017-12-05 21:47 UTC
# Bug

## Description

On a fresh Tails (3.3+) install, `./securedrop-admin tailsconfig` does not mark `source.desktop` and `journalist.desktop` as trusted.
## Steps to Reproduce

- Install Tails 3.3 
- Install SecureDrop 
- Run `./securedrop-admin tailsconfig'
- Observe the lack of trusted source and journalist icons on desktop

## Expected Behavior

Desktop icons should be trusted after running `./securedrop-admin tailsconfig` and not require further user intervention.

## Actual Behavior

Users must either: 
- Reboot the Admin tails workstation
- Restart the network interface

## Comments

Perhaps we add a final down/up for network interfaces once `./securedrop-admin tailsconfig` changes trust settings for desktop icons.

**Comment by kushaldas** [comment] 2017-12-15 15:53
It seems just restarting the NetworkManager at the end of the installation (after setting up NM role) is the easiest option. Any problem in that one may think of?

**Comment by kushaldas** [comment] 2017-12-20 11:58
A did a fresh install on a fresh tails vm today. After the `tailsconfig` command created the new tor network details, it actually restarted the tor and that made the desktop icons trusted. Means I could not reproduce the bug.

**Comment by redshiftzero** [comment] 2018-01-10 23:54
I was able to reproduce this bug report on Tails 3.4 during QA of SecureDrop 0.5.1-rc1. In my testing, after a reboot, once the network came up, the Tails desktop icons were displayed again. We should add a note in the documentation for admins and journalists indicating that they need to reboot their Tails sticks after running `securedrop-admin tailsconfig` (that doesn't close this bug, but it at least provides a workaround for current users).

**Comment by redshiftzero** [comment] 2018-01-10 23:57
I'm curious why you didn't hit this @kushaldas - did you see this in this QA cycle on Tails 3.4 (if you made a fresh Tails VM)?

**Comment by zenmonkeykstop** [comment] 2020-01-31 23:51
`tailsconfig` now always runs the network hook, as opposed to conditionally when the hook changes. This would explain the different experiences above, and the icons are now always trusted after either `tailsconfig`, reboot, or a network change.

Closing ticket as resolved in #4745

**Closed by zenmonkeykstop** 2020-01-31 23:51 UTC
Labels: bug, ops/deployment
