### ISSUE TITLE
Error while requeing for secure deletion did not happen on rc2

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#4772] opened 2019-09-09 17:24 UTC
## Description

This is update from v2 to v2+v3 (1.0.0-rc2).

#### Testing automatic requeuing of interrupted deletions

Establish two SSH connections to the app server. In one, become root with `sudo su -` and in the other become www-data with `sudo -u www-data bash`. In the `www-data` shell:

Activate the securedrop-app-code virtualenv: `. /opt/venvs/securedrop-app-code/bin/activate`

`cd /var/www/securedrop`

Create a big file that will take a while to delete: `dd if=/dev/zero of=/var/lib/securedrop/store/bigfile bs=1M count=1000`

Submit a job to delete it:

```
python3
>>> import rm
>>> import worker
>>> q = worker.create_queue()
>>> q.enqueue(rm.secure_delete, "/var/lib/securedrop/store/bigfile")
```

Exit Python.

In the root shell:
Reboot, then reconnect.

Look at the rqrequeue log: less /var/log/securedrop_worker/rqrequeue.err --

## Expected Behavior

 at the end you should see lines like this:
```
2019-08-08 17:31:01,118 INFO Running every 60 seconds.
2019-08-08 17:31:01,141 INFO Requeuing job <Job 1082e71f-7581-448c-b84b-027e55b4ef8e: rm.secure_delete('/var/lib/securedrop/store/bigfile')>
2019-08-08 17:32:01,192 INFO Skipping job 1082e71f-7581-448c-b84b-027e55b4ef8e, which is already being run by worker rq:worker:6a6b548310f948e291fa954743b8094f
```

## Actual Behavior

The following error messages.

```
22:49:00 default: rm.secure_delete('/var/lib/securedrop/store/bigfile') (1f9ee095-9a85-4adc-a7b2-f8163261db19)
shred: /var/lib/securedrop/store/bigfile: failed to open for writing: Permission denied
22:49:01 subprocess.CalledProcessError: Command '['shred', '-z', '-n', '30', '-u', '/var/lib/securedrop/store/bigfile']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/var/www/securedrop/rm.py", line 83, in secure_delete
    shred(t)
  File "/var/www/securedrop/rm.py", line 51, in shred
    subprocess.check_call(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['shred', '-z', '-n', '30', '-u', '/var/lib/securedrop/store/bigfile']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/var/www/securedrop/rm.py", line 83, in secure_delete
    shred(t)
  File "/var/www/securedrop/rm.py", line 51, in shred
    subprocess.check_call(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['shred', '-z', '-n', '30', '-u', '/var/lib/securedrop/store/bigfile']' returned non-zero exit status 1
22:49:01 Cleaning registries for queue: default
22:49:08 Worker rq:worker:59597f7b6a31457baf3bcb757b623447: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/worker.py", line 470, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/worker.py", line 521, in dequeue_job_and_maintain_ttl
    job_class=self.job_class)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/queue.py", line 469, in dequeue_any
    result = cls.lpop(queue_keys, timeout, connection=connection)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/queue.py", line 441, in lpop
    result = connection.blpop(queue_keys, timeout)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/client.py", line 1618, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/connection.py", line 687, in read_response
    response = self._parser.read_response()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/connection.py", line 298, in read_response
    response = self._buffer.readline()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/connection.py", line 230, in readline
    self._read_from_socket()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/redis/connection.py", line 176, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
22:49:56 Worker rq:worker:4ff52eb00bdf49c28f7a3a68b9c0d565: started, version 1.1.0
22:49:56 *** Listening on default...


```

## Comments

Suggestions to fix, any other relevant information.

**Comment by rmol** [comment] 2019-09-09 17:28
@kushaldas Looks like a permission problem. Are you sure you created the file in the `www-data` shell?

**Comment by redshiftzero** [comment] 2019-09-10 19:27
I just tested in a fresh 1.0.0-rc2 install on prod VMs and am unable to reproduce - I think this is error due to permissions as @rmol points out. I'm going to close this - if someone else sees it in their test environment please re-open.

**Closed by redshiftzero** 2019-09-10 19:27 UTC
Labels: QA: Release
