### ISSUE TITLE
make dev failing with GNUPG error

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5961] opened 2021-05-25 13:51 UTC
## Description

`make dev` is failing with GNUPG errors after adding the dummy sources.

## Steps to Reproduce

- [ ]  `make dev`

## Expected Behavior

It should start the application properly.

## Actual Behavior

```
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Traceback (most recent call last):
  File "./loaddata.py", line 471, in <module>
    load(parse_arguments())
  File "./loaddata.py", line 390, in load
    add_sources(args, journalists)
  File "./loaddata.py", line 344, in add_sources
    submit_message(source, random.choice(journalists) if seen_message_count > 0 else None)
  File "./loaddata.py", line 182, in submit_message
    fpath = current_app.storage.save_message_submission(
  File "/root/code/securedrop/securedrop/store.py", line 373, in save_message_submission
    current_app.crypto_util.encrypt(message, [self.__gpg_key], msg_loc)
  File "/root/code/securedrop/securedrop/crypto_util.py", line 298, in encrypt
    raise CryptoException(out.stderr)
crypto_util.CryptoException: [GNUPG:] FAILURE option-parser 33554433
gpg: missing argument for option "--recipient"

make: *** [Makefile:185: dev] Error 1
```

**Comment by rmol** [comment] 2021-05-25 14:31
I pulled latest `develop` (b6dcf555bee47c585196f09a512a052791246e66) and ran `make dev` several times. There were no errors at startup, and I was able to visit the source interface, create a new source, and submit without any errors.

**Comment by conorsch** [comment] 2021-05-25 19:29
Also cannot reproduce. I made sure to run `docker system prune --all --volumes --force` beforehand, so the container was built fresh. I didn't interact with the app after the container came up, but no errors were shown during creation.

**Comment by eloquence** [comment] 2021-05-26 16:01
Closing until we get a clean repro.

**Closed as completed by eloquence** 2021-05-26 16:01 UTC
Labels: needs/reproducing

**Comment by kushaldas** [comment] 2021-05-27 07:18
After cleaning all docker related things, I got a new error now:

```
Successfully tagged securedrop-test-focal-py3:latest
************************************************************
Exposed Docker ports will be available on localhost with
Port offset: 0
Source interface: 8080
Journalist interface: 8081
VNC: 5909
************************************************************
███ Generating securedrop/config.py...

chown: changing ownership of '/var/lib/securedrop/keys/S.gpg-agent': No such file or directory
chown: changing ownership of '/var/lib/securedrop/keys/S.gpg-agent.browser': No such file or directory
chown: changing ownership of '/var/lib/securedrop/keys/S.gpg-agent.ssh': No such file or directory
make: *** [Makefile:185: dev] Error 1

```

**Comment by kushaldas** [comment] 2021-05-27 07:27
and after a reboot and cleaning of everything again, things are now working

**Comment by chamalis** [comment] 2023-07-27 10:35
I have the same issue which persists after "docker prunes" and reboots.

The issue seems to be that the `using_keys_with_fingerprints` passed down to [EncryptionManager._encrypt](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/encryption.py#L186) function, during the test data creation, is the default value in [config.py ](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/config.py.example#L42)(enclosed in a list of course): `['{{securedrop_app_gpg_fingerprint}}']`

```
#11 [7/7] RUN if test user != root ; then useradd --no-create-home --home-dir /tmp --uid 1000 user && echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers ; fi &&     chown -R user.user /opt/venvs/
#11 DONE 42.6s

#12 exporting to image
#12 exporting layers
#12 exporting layers 2.7s done
#12 writing image sha256:05fa0502d34c0e4d64a1e44aacae51236c051b4f142633ccae8a34163090a0d9 done
#12 naming to docker.io/library/securedrop-slim-focal-py3 0.0s done
#12 DONE 2.7s
************************************************************
Exposed services will be available on localhost at
Source interface: http://127.0.0.1:8080
Journalist interface: http://127.0.0.1:8081
************************************************************
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at /opt/venvs/securedrop-app-code/bin/python3
📡 Using build options compatibility from pyproject.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
📖 Found type stub file at redwood.pyi
📦 Built wheel for CPython 3.8 to /path_to_securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Processing /path_to_securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Installing collected packages: redwood
Successfully installed redwood-0.1.0
WARNING: You are using pip version 21.1.1; however, version 23.2.1 is available.
You should consider upgrading via the '/opt/venvs/securedrop-app-code/bin/python3 -m pip install --upgrade pip' command.
main: /var/lib/securedrop/db.sqlite
gpg: keybox '/var/lib/securedrop/keys/pubring.gpg' created
gpg: key CC40EF1228271441: public key "SecureDrop Test/Development (DO NOT USE IN PRODUCTION)" imported
gpg: Total number processed: 1
gpg:               imported: 1
Created journalist (username=journalist, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=True)
Created journalist (username=dellsberg, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Traceback (most recent call last):
  File "./loaddata.py", line 460, in <module>
    load(parse_arguments())
  File "./loaddata.py", line 379, in load
    add_sources(args, journalists)
  File "./loaddata.py", line 332, in add_sources
    submit_message(source, secrets.choice(journalists) if seen_message_count > 0 else None)
  File "./loaddata.py", line 181, in submit_message
    fpath = Storage.get_default().save_message_submission(
  File "/path_to_securedrop/securedrop/store.py", line 376, in save_message_submission
    EncryptionManager.get_default().encrypt_source_message(
  File "/path_to_securedrop/securedrop/encryption.py", line 138, in encrypt_source_message
    self._encrypt(
  File "/path_to_securedrop/securedrop/encryption.py", line 192, in _encrypt
    raise GpgEncryptError(out.stderr)
encryption.GpgEncryptError: [GNUPG:] FAILURE option-parser 33554433
gpg: missing argument for option "--recipient"

make: *** [Makefile:239: dev] Error 1
```

If I hardcode the fingerprint (`CC40FF1228271441`) of `securedrop/securedrop/tests/files/test_journalist_key.pub `, like this (or change it in `config.py`):
```python
    def _encrypt(
        self,
        using_keys_with_fingerprints: List[str],
        plaintext_in: typing.IO,
        ciphertext_path_out: Path,
    ) -> None:
        # Remove any spaces from provided fingerprints GPG outputs fingerprints
        # with spaces for readability, but requires the spaces to be removed
        # when using fingerprints to specify recipients.
        sanitized_key_fingerprints = [fpr.replace(" ", "") for fpr in using_keys_with_fingerprints]

        out = self._gpg.encrypt(
            plaintext_in,
            'CC40FF1228271441',  # *sanitized_key_fingerprints,
            output=str(ciphertext_path_out),
            always_trust=True,
            armor=False,
        )
        if not out.ok:
            raise GpgEncryptError(out.stderr)
```
the issue turns to:
`encryption.GpgEncryptError: gpg: CC40FF1228271441: skipped: No public key`, 
despite the fact that it seems to have already been imported:

```
export DOCKER_BUILD_VERBOSE=true
(sdrop) user@hostname:~/path_to_securedrop$ make dev
███ Starting development server...
[+] Building 276.8s (12/12) FINISHED                                                                                     docker:default
 => [internal] load build definition from SlimDockerfile                                                                           0.0s
 => => transferring dockerfile: 2.57kB                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 88B                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd  2.7s
 => [1/7] FROM docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd                    6.3s
 => => resolve docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd                    0.0s
 => => sha256:eaead16dc43bb8811d4ff450935d607f9ba4baffda4fc110cc402fa43f601d83 28.58MB / 28.58MB                                   5.6s
 => => sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd 1.42kB / 1.42kB                                     0.0s
 => => sha256:b25ef49a40b7797937d0d23eca3b0a41701af6757afca23d504d50826f0b37ce 529B / 529B                                         0.0s
 => => sha256:680e5dfb52c74a1fbc99c2922c8e25b5736e6cd1a3d9430890d52a4f8f44087a 1.46kB / 1.46kB                                     0.0s
 => => extracting sha256:eaead16dc43bb8811d4ff450935d607f9ba4baffda4fc110cc402fa43f601d83                                          0.5s
 => [internal] load build context                                                                                                  0.0s
 => => transferring context: 113.98kB                                                                                              0.0s
 => [2/7] RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y                        apache2-dev  118.0s
 => [3/7] RUN TMPDIR=`mktemp -d` && cd ${TMPDIR}         && curl --proto '=https' --tlsv1.2 -OO -sSf https://static.rust-lang.or  64.2s
 => [4/7] COPY requirements requirements                                                                                           0.0s 
 => [5/7] RUN python3 -m venv /opt/venvs/securedrop-build &&     /opt/venvs/securedrop-build/bin/pip3 install --no-deps --require  8.2s 
 => [6/7] RUN python3 -m venv /opt/venvs/securedrop-app-code &&     /opt/venvs/securedrop-app-code/bin/pip3 install --no-deps --  59.5s 
 => [7/7] RUN if test user != root ; then useradd --no-create-home --home-dir /tmp --uid 1000 user && echo "user ALL=(ALL) NOPAS  14.7s 
 => exporting to image                                                                                                             3.1s 
 => => exporting layers                                                                                                            3.1s 
 => => writing image sha256:ec5fe5ef92061bb9b7f47e33af7edd651cc72655d071770cee0d6565d255f04f                                       0.0s 
 => => naming to docker.io/library/securedrop-slim-focal-py3                                                                       0.0s 
************************************************************                                                                            
Exposed services will be available on localhost at
Source interface: http://127.0.0.1:8080
Journalist interface: http://127.0.0.1:8081
************************************************************
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at /opt/venvs/securedrop-app-code/bin/python3
📡 Using build options compatibility from pyproject.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
📖 Found type stub file at redwood.pyi
📦 Built wheel for CPython 3.8 to /home/user/path_to_securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Processing /home/user/path_to_securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Installing collected packages: redwood
Successfully installed redwood-0.1.0
WARNING: You are using pip version 21.1.1; however, version 23.2.1 is available.
You should consider upgrading via the '/opt/venvs/securedrop-app-code/bin/python3 -m pip install --upgrade pip' command.
main: /var/lib/securedrop/db.sqlite
gpg: keybox '/var/lib/securedrop/keys/pubring.gpg' created
gpg: key CC40EF1228271441: public key "SecureDrop Test/Development (DO NOT USE IN PRODUCTION)" imported
gpg: Total number processed: 1
gpg:               imported: 1
Created journalist (username=journalist, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=True)
Created journalist (username=dellsberg, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Traceback (most recent call last):
  File "./loaddata.py", line 460, in <module>
    load(parse_arguments())
  File "./loaddata.py", line 379, in load
    add_sources(args, journalists)
  File "./loaddata.py", line 332, in add_sources
    submit_message(source, secrets.choice(journalists) if seen_message_count > 0 else None)
  File "./loaddata.py", line 181, in submit_message
    fpath = Storage.get_default().save_message_submission(
  File "/home/user/path_to_securedrop/securedrop/store.py", line 376, in save_message_submission
    EncryptionManager.get_default().encrypt_source_message(
  File "/home/user/path_to_securedrop/securedrop/encryption.py", line 138, in encrypt_source_message
    self._encrypt(
  File "/home/user/path_to_securedrop/securedrop/encryption.py", line 192, in _encrypt
    raise GpgEncryptError(out.stderr)
encryption.GpgEncryptError: gpg: CC40FF1228271441: skipped: No public key
[GNUPG:] INV_RECP 1 CC40FF1228271441
[GNUPG:] FAILURE encrypt 9
gpg: [stdin]: encryption failed: No public key

make: *** [Makefile:239: dev] Error 1
```
