### ISSUE TITLE
Logged-out user is shown "You were logged out due to inactivity" and redirected to index page

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop#5741] opened 2021-01-22 23:56 UTC
## Description

Clicking login button when you are logged out doesn't take you to the login page.

## Steps to Reproduce

1. Configure session timeout to be 2 minutes instead of the default 120 minutes.
2. Restart Apache `apachectl restart`
3. Log into the Source Interface
4. Go to submission page and click log-out button
5. Wait for just over 2 minutes
6. Click log-in button

## Expected Behavior

For the "/login" page to show up.

## Actual Behavior

You are sent to the index page and have to click on the log-in button again.

**Comment by sssoleileraaa** [comment] 2021-01-23 00:01
Also, clicking the "Get Started" button doesn't do anything after you are logged out and redirected to the index page.

## Steps to Reproduce

1. Run through STR above
2. Click "Get Started" button

## Expected Behavior

For the "/generate" page to show up.

## Actual Behavior

You remain on the index page.

**Comment by eloquence** [comment] 2021-01-23 00:03
(Cannot reproduce either issue in the Docker env, FWIW, neither on `develop` nor `release/1.7.0` branch)

**Comment by sssoleileraaa** [comment] 2021-01-23 00:16
I updated the STR to say to wait for the timeout period of 2 minutes

**Comment by sssoleileraaa** [comment] 2021-01-23 00:17
And this doesn't happen on develop - just rc4

**Comment by eloquence** [comment] 2021-01-23 00:21
Potentially related: #5716.

**Comment by sssoleileraaa** [comment] 2021-01-23 00:57
One more related STR, which is actually copied from the 1.7.0 Test Plan to make sure that the session expiration message is only displayed when signed in:

## Steps to Reproduce

0. Like the STR in this PR description, set session timeout to 2 minutes and restart Apache.
1. Click the New Identity icon in the Tor Browser to clear current browser data and visit the Source Interface again
2. Click Get Started
3. Wait slightly over 2 minutes
4. After the codename generation page is displayed
5. Visit the Source Interface index page again

## Expected Behavior

No session expiry error message is displayed

## Actual Behavior

Session expiry error message is displayed

**Comment by emkll** [comment] 2021-01-25 15:33
Thanks for opening @creviera , I can reproduce the behavior you describe here. As you mentioned in #5716 , this appears to be the same underlying issue. In this case, the session expiry will always redirect you to the index page and not the login page:
https://github.com/freedomofpress/securedrop/blob/4df72e72f9b0e25a11696bafe3e960bf754cc38c/securedrop/source_app/__init__.py#L139-L141

> Also, clicking the "Get Started" button doesn't do anything after you are logged out and redirected to the index page.

Confirmed, I also see this, in this case, show_expiration_message is set to false.

Given the several edge cases identified here and in #5716, while I don't think the issues are severe enough to address in time for the 1.7.0 release, they do highlight the need take a broader look at session management as proposed in https://github.com/freedomofpress/securedrop/pull/5692

**Comment by sssoleileraaa** [comment] 2021-01-26 00:59
Yep, thanks @emkll for the code reference. The fix should ensure that we only show the "You were logged out due to inactivity" popup and redirect to the index page on user action when we _actually_ log a user out. If the user is already logged out as in the STRs above, we should not show them this message or redirect user action. It would also be an improvement to redirect immediately when the user session expires.

**Comment by sssoleileraaa** [comment] 2021-01-26 01:01
I just confirmed that this is happening on 1.6.0 so I will update the Issue title and description.

**Comment by eloquence** [comment] 2021-02-03 01:35
Relatively low priority edge case, so parking in near-term backlog for now.

**Comment by nabla-c0d3** [comment] 2021-09-25 16:31
This was fixed by #5694 and #5695.

**Comment by eloquence** [comment] 2021-09-29 18:10
Thanks, closing accordingly, we'll test session management extensively during QA as well.

**Closed as completed by eloquence** 2021-09-29 18:10 UTC
