### ISSUE TITLE
Intermittent Travis test failures (Directory not empty: '/tmp/securedrop/keys')

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#844] opened 2015-01-23 01:18 UTC
Recently it seems to me that Travis has begun failing more often than it should. Most of the failures are not actual test failures, but appear to be related to the setup and teardown for each test. Re-running the Travis build usually results in all tests passing.

I will post relevant logs in comments on this issue as they occur. It does not appear to be possible to recover the logs from a failed build once you've restarted it :disappointed:

**Comment by garrettr** [comment] 2015-01-26 23:19
Here's an example log for one of these intermittent failures: https://gist.github.com/garrettr/65271f6b1c31b03487a3

**Comment by garrettr** [comment] 2015-01-29 02:27
Another log for a similar intermittent failure: https://gist.github.com/garrettr/f0a0a603ee025ba16223

**Comment by garrettr** [comment] 2015-01-30 22:01
Here's another example, which looks like it might be a different flavor than the first two: https://gist.github.com/garrettr/04d58b02489c185c3081

**Comment by garrettr** [comment] 2015-01-30 22:19
Sometimes Pip is flaky too: https://gist.github.com/garrettr/dbe8e77b91fa6db1c4f9. I'm not sure if there's anything we could do about that (besides switching to a better CI system that allows us to use custom base images...)

**Comment by garrettr** [comment] 2015-02-05 16:02
Another rmtree-related intermittent test failure: https://gist.github.com/garrettr/ad6c791748abc310d267

**Comment by garrettr** [comment] 2015-02-05 17:26
And another one: https://gist.github.com/garrettr/3b778b308213f19c8e3b

**Comment by garrettr** [comment] 2015-02-24 02:19
This is an interesting one, in test_regenerate_valid_lengths: https://gist.github.com/garrettr/28f00ae6a2f45d44692a

**Comment by garrettr** [comment] 2015-03-27 01:00
Adding p-high, since this makes the CI less valuable and repeatedly wastes developer time.

**Comment by garrettr** [comment] 2015-03-31 00:21
Started looking at this today. There are approximately 3 distinct classes of errors reported in this issue, but the most common by far is errors in `shutil.rmtree` when it's called from `common.clean_root`.

Here's a [recent traceback](https://gist.github.com/garrettr/90c2ffb142f3ee69da20). I have a theory about what's going on here. I think this is a race condition caused by python-gnupg's use of daemon threads, similar to my theory about the cause of [this other intermittent test issue](https://github.com/freedomofpress/securedrop/issues/618#issuecomment-60293098).

Here's what I think happens:

1. Test calls some python-gnupg functions, which shell out to gnupg. python-gnupg [uses daemon threads](https://github.com/isislovecruft/python-gnupg/blob/2beac24161b07e40642d93f5d85faeb9740f78db/gnupg/_meta.py#L716), which means the process may shut down before the threads have completed.
2. The gnupg processes take variable amounts of time because they are doing crypto operations (especially key gen, since the time that takes depends on `/dev/random`'s blocking behavior).
3. Sometimes the test finishes before gpg finishes doing something that the test asked it to do.
4. The test's `tearDown` enters `clean_root`, which calls `shutil.rmtree`.
5. `shutil.rmtree` calls `os.listdir` and gets a list of files in the `SECUREDROP_DATA_ROOT`. It starts recursively deleting files.
6. gpg finishes, and cleans up some temporary files (e.g. the lockfile `/tmp/securedrop/keys/pubring.gpg.lock` and whatever the heck `/tmp/securedrop/keys/.#lk0x7f187816dac0.testing-worker-linux-e7a62211-2-2367-linux-7-56489264.17090` is).
7. `shutil.rmtree` is still deleting things recursively, using the list of files it got from `os.listdir` before gpg exited. This is the race condition.
8. It attempts to delete a file that was deleted after `os.listdir`, when gpg exited, and results in the errors we are seeing here.

**Comment by garrettr** [comment] 2015-03-31 00:27
tests that failed in `shutil.rmtree`:

- TestIntegration.test_delete_collection
- TestIntegration.test_filenames (2x)
- TestSource.test_regenerate_invalid_lengths
- TestSource.test_submit_message
- TestStore.test_get_zip

There is not an obvious pattern here - the failures are spread across a variety of modules and test functions. Note that all test functions initialize gpg and import keys, due to `common.init_gpg`.

**Comment by garrettr** [comment] 2015-05-07 19:13
Here's a new one: https://gist.github.com/garrettr/59ad3112df829887caa4

**Comment by fowlslegs** [comment] 2017-03-02 23:05
@garrettr Removed this one, then had second thoughts. Think you should make the call on the status of this one + it's targeted milestone.

**Comment by conorsch** [comment] 2017-03-02 23:18
@fowlslegs I'm not convinced this is actually a problem anymore. We've made a lot of changes to the app test suite, and we tend to trust Travis's failures to mean "take a close look at this PR." Very occasionally I have to manually retrigger a Travis build—is that something you've been doing more frequently than I? If not, we may be able to close this until it becomes a problem again.

**Comment by fowlslegs** [comment] 2017-03-02 23:31
@conorsch I'm inclined to agree, but want to wait for @garrettr to chime in.

**Comment by dachary** [comment] 2017-08-29 11:51
We're still seeing [OSError: [Errno 39] Directory not empty: '/tmp/securedrop/keys'](https://gist.github.com/garrettr/65271f6b1c31b03487a3) two years later. It's relatively rare but happens once every 50 runs or so (gut feeling, I'm not collecting stats ;-).

**Comment by dachary** [comment] 2017-08-29 12:11
> I have a theory about what's going on here. I think this is a race condition caused by python-gnupg's use of daemon threads

This was fixed with https://github.com/freedomofpress/securedrop/pull/2123 but the problem remains.

**Comment by dachary** [comment] 2017-08-29 14:19
Yeah ! Have a reproducer. It takes a few hours but it's here ! Points to async gpg events indeed: must be in the background and no longer a child of the process. 
<pre>
time while : ; do pytest tests || break; done
</pre>

<pre>
================================================================================================== FAILURES ===================================================================================================
__________________________________________________________________________ TestJournalistApp.test_delete_source_deletes_docs_on_disk __________________________________________________________________________

self = <tests.test_journalist.TestJournalistApp testMethod=test_delete_source_deletes_docs_on_disk>

    def setUp(self):
>       utils.env.setup()

tests/test_journalist.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/env.py:50: in setup
    create_directories()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def create_directories():
        """Create directories for the file store and the GPG keyring.
        """
        for d in (config.SECUREDROP_DATA_ROOT, config.STORE_DIR,
                  config.GPG_KEY_DIR, config.TEMP_DIR):
            if not isdir(d):
>               os.mkdir(d)
E               OSError: [Errno 17] File exists: '/tmp/securedrop/keys'

tests/utils/env.py:33: OSError
============================================================================================== warnings summary ===============================================================================================
:171
  'pytest_runtest_makereport' hook uses deprecated __multicall__ argument

None
  pytest_funcarg__caplog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
  pytest_funcarg__capturelog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
======================================================================= 1 failed, 187 passed, 41 skipped, 3 warnings in 166.54 seconds ========================================================================

real	111m33.239s
user	42m52.663s
sys	10m0.710s
</pre>

**Comment by dachary** [comment] 2017-08-31 12:12
After running the reproducer during hours the error did not show. It obviously is a case of the gnupg subprocess still working on the key subdirectory when teardown() is called. When rmtree fails to remove the key directory because it is not empty, it means gnupg added a file *after* rmtree removed all files in the key directory. When **create_directories** cannot create the key directory because it already exists, it means gnupg managed to recreate it after rmtree from the previous test killed it.

The gnupg python module indead runs [gnupg asynchronously](https://github.com/isislovecruft/python-gnupg/blob/master/gnupg/_meta.py#L726) and has two threads pending to read/write to it. However, even though these threads are daemonic (i.e. the python process could exit without waiting for them), they are returned by [threading.enumerate()](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/tests/utils/env.py#L66) and joined() before rmtree is run, therefore providing a guarantee that no gnupg process is pending.

The race is hidden not too far from this code path. The plot thickens.

**Comment by dachary** [comment] 2017-08-31 12:39
I may have run the reproducer on a branch that did not have the **join** in the teardown. I'll wait until the error shows up once more to be sure it's still here. Right now I can't see how it could happen. And joining all threads returned by threading.enumerate() in teardown seems to be an effective way to ensure there is no overlap.

**Comment by dachary** [comment] 2017-09-05 14:59
It happened again ! Attaching the full log, it will hopefully give us something to work with :-) 

[arg.txt.gz](https://github.com/freedomofpress/securedrop/files/1277834/arg.txt.gz)

**Comment by dachary** [comment] 2017-09-06 09:47
So, this turns out to be a race due to the fact that the redis triggered job loads gnupg which tries to create directories although its only responsibility should be to remove files asynchronously.

IMO the right fix is to get rid of redis + workers and have a thread in charge of removing files asynchronously to not block the main process when/if it takes time. 

The race we are observing has been extraordinarily difficult to find, the code path leading to the actual error is poorly tested, packaging and running the worker is ad-hoc, redis and the worker are two daemons required to run tests and that makes them more complicated to maintain and stabilize and any error occuring on a redis delegated task is serialized in a cryptic way in the **failed** queue of [rq](http://python-rq.org/). The minimal fix would be to move the removal functions from store.py to an independent file. It would also make sense to improve the conditions under which an error can be diagnosed and fix by changing the worker daemon to catch and display exceptions in a log instead of silently ignoring them. It would also be good for tests to be able to monitor the remaining jobs in the worker.py queue (yes, both the worker daemon and the worker client have the same name which is a bit confusing, renaming one of them would help) and wait for them to complete (or assert their failure).

This effort to consolidate the current code path is, IMHO, overkill. It would be less work and lead to a more stable and maintainable implementation to just remove redis and the worker. Instead a **Shredder** class could provide the same functionality. An instance of the **Shredder** class is created by the journalist app with a **config.SHREDDER_DIR**. It creates a thread that removes (via **srm**) all files from this directory and sleeps on inotify when there is nothing left. The journalist interface then calls the **rm** method of the **Shredder** instance which **mv** the file/directory to **config.SHREDDER_DIR**: this is an atomic and instantaneous system call (assuming the same file system, otherwise it just fails). If the journalist process crashes and some files are left in **config.SHREDDER_DIR** they will be taken care of when the journalist app restarts.

**Comment by dachary** [comment] 2017-09-06 14:51
See also #1469 for a another discussion. Not motivated by an actual bug but raising similar concerns.

**Closed** 2017-09-14 21:01 UTC
Labels: app, P-high, tests

**Comment by dachary** [comment] 2017-09-14 21:50
Such an emotional moment when a long standing bug is resolved. Thanks @redshiftzero :-)
