### ISSUE TITLE
Bug in Vagrant 1.8.1 breaks provisioning VM groups

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#1241] opened 2016-01-27 01:26 UTC
The example command `vagrant up /staging$/` from our development docs is currently broken in Vagrant 1.8.1 on both Linux and OSX.

Issue filed upstream here: https://github.com/mitchellh/vagrant/issues/6828

Filing this as an acknowledgment of the issue in case any one else encounters it; when it gets fixed upstream we can close this out, but possibly include a note advising against using that Vagrant version.

**Comment by conorsch** [comment] 2016-01-27 15:41
Looks like this is an upstream issue that isn't reliably reproduceable. For instance, I can't reproduce it on my machine, and I'm running Vagrant 1.8.1, and the same is true for one of the maintainers. If you're affected, @ageis, provide some debug logs and platform information on the upstream issue and we'll compare notes.

**Comment by garrettr** [comment] 2016-01-27 17:03
I'm also having this problem with Vagrant 1.8.1 on Mac, so I did what @conorsch suggested and commented on the upstream bug with my debug logs: https://github.com/mitchellh/vagrant/issues/6828#issuecomment-175747531

**Comment by garrettr** [comment] 2016-03-03 21:57
Found a workaround in one of the various issues on the upstream Vagrant repo. If you specify `--no-install-provider`, multimachine provisioning with regex works again. e.g.

```
vagrant up --no-install-provider /staging$/
```

works for me, event hough `vagrant up /staging$/` does not.

`¯\_(ツ)_/¯`

**Comment by conorsch** [comment] 2016-05-12 17:17
Astounding though it is, this regression is still live in the most recent versions of vagrant. To keep things simple, we can just update the examples in the dev docs to use full machine names, rather than regex, e.g. `vagrant up --no-provision app-staging mon-staging`.

**Comment by garrettr** [comment] 2016-05-12 20:32
@conorsch Yes, I sadly agree that would be the best (for now). I asked if there's an ETA for Vagrant 1.8.2, which includes a fix for this, on the upstream repo: https://github.com/mitchellh/vagrant/issues/6828#issuecomment-218876744.

**Comment by conorsch** [comment] 2016-05-19 22:37
@fowlsegs was bitten by this recently. We should remove all regexp-formatted vagrant commands from the dev docs and use explicit host groups instead. I don't really care if Hashicorp patch this; let's just stick with the explicit version, since that seems more stable.

Another reason we want to use the explicit version: since Vagrant 1.8(ish), provisioning happens per-host even if not all target hosts have been created. That's foolish. @fowlslegs mentioned this work around in #1304:

```
vagrant up {app,mon}-staging --no-provision && vagrant provision {app,mon}-staging
```

That's fine, but in the context of the developer docs, it's more explicit to use two commands:

```
vagrant up --no-provision app-staging mon-staging
vagrant provision app-staging mon-staging
```

If I were a developer accustomed to the vagrant workflow, that would be explicit and intuitive to me, so I think that's our best bet. Thoughts, @fowlsegs?

**Comment by fowlslegs** [comment] 2016-05-20 02:24
The second block lgtm. We shouldn't have to change it back ever. Let's not depend on upstream to keep anything working as we'd like besides that block.

**Comment by garrettr** [comment] 2016-06-25 00:46
Rejoice! Vagrant 1.8.3 was released on June 10, and it fixes https://github.com/mitchellh/vagrant/issues/6908 (see [Vagrant changelog](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md)).

Given this exciting development, I think all we need to do to resolve this issue is update the documentation to recommend that developers use Vagrant >= 1.8.3.

**Comment by conorsch** [comment] 2016-08-22 07:28
Mere days after 1.8.3, Vagrant 1.8.4 was released, which fixed a rather important bug related to bundler version constraints. Therefore let's update the docs to say Vagrant >= 1.8.4. Running under 1.8.4, the `vagrant provision /staging/` syntax works again.

**Closed** 2016-08-26 06:02 UTC
Labels: docs
