### ISSUE TITLE
Finalize & Publish Source Guide

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4259] opened 2019-03-13 07:03 UTC
## Description

Long long ago and on a pad far far away, a _Source Guide_ was once drafted. Outsiders reviewed it. Feedback was offered that it felt... well, perhaps a bit paranoid. "Espionage-y" was employed as an adjective. These ancient texts are in fact archived in an FPF GDoc that @conorsch recently excavated. Many current contributors have ideas—while @zenmonkeykstop and @huertanix I'm told, have mused of interests in refining and publishing something. As cycles permit.

TBD text prompts on the website could sure point to something useful, and it'd be great to offer newsrooms something friendly and plain-language-y to link new Sources to. 

## User Research Evidence

Specific to this specific concern w/in SD, nope.
Anecdotal evidence? Sure! Contributor opinions? Many!

Discussion had in [**07 March 2019 UX call**](https://github.com/freedomofpress/securedrop-ux/wiki/UX-meeting-20190307) that @bumbleblue, @ninavizz, @eloquence, @harrislapiroff, @redshiftzero, @creviera and others attended, made this need clear as a near(ish)-term opportunity not to be overlooked.

_On the more general topic of writing & publishing content to guide user decisions? Behold!_
- USDS' most excellent [**Plain Language guide for gov**](https://www.plainlanguage.gov/guidelines/concise/) (equally applicable in InfoSec, imho) 
   - See left-nav on page, and click through the whole thing.
   - [Choosing Words](https://www.plainlanguage.gov/guidelines/words/) is an especially recommended section; click thru the whole left-nav on this one, especially, to guide writing.
      - "Good Writing" and "Usable Writing" are very different. The latter seeks to inform behavior, the prior seeks to provide an experience. 
      - A Source Guide is seeking to inform behavior, not to provide an engaging or educational reading experience. Yes, seeking to inform behavior and educating users about foreign-to-them concepts, must be separated. #pickyourbattles (not 100%, but mostly)
- NielsenNorman Group study ["How Little Do Users Read"](https://www.nngroup.com/articles/how-little-do-users-read/) 
   - Hint: How important "experts" believe things to be, has zero influence on human attention span
- Work with Nina (or any UX practitioner) to properly organize/architect the information.
   - Information Architecture matters... but [what is it](https://www.optimalworkshop.com/guides/what-is-information-architecture)?
   - [IA vs Nav Design](https://www.nngroup.com/articles/ia-vs-navigation/) (another NN article)
     - When it comes time to edit website content, do [tree studies via Optimal Workshop](https://www.optimalworkshop.com/treejack) to test different methods to draw the correct users into the content from the sd.org site

## User Stories

As a person in a high-risk situation who needs to share sensitive documents with a news or advocacy organization, I want some clear guidance on how to use this SecureDrop thing they're saying I should use. I'd specifically like to understand:
- Why SD and not FB Messenger, WhatsApp, or more common/easier methods for communication?
- Why should I trust this thing? Does it run ads, will it track me, and will my data live on it 'forever'?
- What is the basic/overview version of how to use this, and then more details after I've gotten my head around the basics (like, that this is a lot of work and not something I can do with devices I currently own, but it will offer my ass the utmost protection) and have a clear mental-model to work with.

**Comment by ninavizz** [comment] 2019-06-07 22:33
Requesting `information design` `docs` and `Goal: Improve Source Experience` tags added to this. Also cross-referencing #4509 from this, as the two should compliment each other.

**Comment by eloquence** [comment] 2020-10-20 18:32
Closing as duplicate of #490 but thanks for the additional context here, will cross-reference.

**Closed by eloquence** 2020-10-20 18:32 UTC
Labels: docs, goals: improve source experience, information design
