### ISSUE TITLE
securedrop-admin install does not uninstall generic kernel packages

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3135] opened 2018-03-09 17:55 UTC
# Bug

## Description

When performing a clean install on a physical instance with `ubuntu-14.04.5-server-amd64` iso,  the installer does not remove generic kernel packages, in this instance, `linux-image-4.4.0-115-generic`.
## Steps to Reproduce

- Install SecureDrop on Ubuntu Server 14.04.5.
- `ssh app` or `ssh mon`
- `sudo apt list --installed | grep linux-image`
- observe the presence of the generic kernel image

 

## Expected Behavior

These images should be removed as part of the grsecurity role [here](https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/grsecurity/tasks/clean_packages.yml).

## Actual Behavior

The generic images are not removed.

**Comment by conorsch** [comment] 2018-03-09 18:44
Trying to reproduce now. Let's consider forcing the new SD kernel (4.4.115-grsec) via `/etc/default/grub` in the metapackage, so we're certain about what the machines will attempt on next boot.

**Comment by emkll** [comment] 2018-03-09 19:32
Justed tested with 0.6-rc4: Because Ubuntu generic kernels are `4.4.0-115-generic` and apt.freedom.press serves `4.4.115-grsec`, grsec kernels will have precedence on boot.

**Comment by redshiftzero** [comment] 2018-03-12 18:29
Since we've verified the grsec kernels we're releasing tomorrow will have precedence on boot, and we're approaching the release deadline for 0.6.0, I'm moving this to the 0.6.1 milestone (a bugfix release)

**Comment by eloquence** [comment] 2018-03-20 03:20
@redshiftzero, @conorsch and I agreed earlier today that we'd like to skip a 0.6.1 release if at all possible, so removing this issue from the milestone and adding to 0.7.

**Closed** 2018-03-29 17:16 UTC
Labels: QA: Release, bug
