### ISSUE TITLE
File upload limit does not work in the development environment

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1714] opened 2017-05-18 19:32 UTC
# Steps to reproduce

1. Provision development VM
2. Go to source interface
3. Generate a codename
4. Submit a >0.5 GB file

# What should happen

A flashed message should appear indicating that the file is too large for submission.

# What actually happens

The file uploads.

# Comment

Whoever fixes this ideally should definitely write a functional or unit test to guard against future regressions.

**Comment by fowlslegs** [comment] 2017-05-19 19:54
**Edit:** I found [the original implementation](https://github.com/freedomofpress/securedrop/commit/b3486e262f2a4bf7812606bcc01fe61649f068d5) after starting writing this, but I'll keep my original response so to share knowledge and have notes of the research I did. Anyway, finding this was significant because I realized that the file upload limit will not work in develop because it's enforced by Apache. Further, there seems to be no way to serve a response with a custom error message (see [the docs](https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody)), so we won't be able to flash a specific warning message--I presume/hope Apache's own is at least somewhat informative. Anyway, since this is not a bug in production, we have a testinfra test to make sure this is set in the SI Apache config, and we can't choose a custom flashed message, I'm going to close.

Researching this, it seems there is no way to limit file upload size using just HTML.  The `input` element does support the `maxlength` content attribute in some cases, but not when `type="file"` (see https://html.spec.whatwg.org/multipage/forms.html#the-input-element). OTOH, we can and should put a limit on the message size, which uses the `textarea` element, which supports  `maxlength` content attribute.

The best we can do w/o JS is to have the server reject uploads after 500MB, but in this case the client won't get the flashed warning for possibly hours that their submission was rejected for being over the limit; this doesn't seem like a good scenario. We can make the text below the box a little bit more informative/explicit/scary to try to prevent people from making this mistake, but I can't think of anything else that wouldn't involve using JS to prevent someone waiting possibly hours before having their submission rejected.

**Comment by garrettr** [comment] 2017-05-25 02:26
The max file size is currently implemented in the [Apache configuration](https://github.com/freedomofpress/securedrop/blob/49b8fb8793a7f5ec755d04dc98d04037b7ec9697/install_files/ansible-base/roles/app/templates/sites-available/source.conf#L23-L24) for the Source Interface via the [`LimitRequestBody` directive](https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody). For background, this is implemented by checking the `Content-Length` header of the HTTP response and returning an error response for requests that exceed the limit.

Since the development environment uses Flask's debugging web server instead of Apache, the max file size is not enforced in the development environment. I would recommend trying to reproduce this error in the staging or production environments - you should see a generic (and probably confusing/unhelpful) error page when uploading a file over the limit. The error page is generic because it is being returned by Apache, not Flask.

It should be possible to return a more helpful error message for file uploads that exceed the limit by implementing this restriction in Flask instead of in Apache. This can be done via the [`MAX_CONTENT_LENGTH`](http://flask.pocoo.org/docs/0.12/patterns/fileuploads/#improving-uploads) application configuration setting. If a file upload exceeds the limit, we could catch the resulting `RequestEntityTooLarge` exception and use that to flash a helpful error message to the source.

The other thing to keep in mind is that we [override](https://github.com/freedomofpress/securedrop/blob/49b8fb8793a7f5ec755d04dc98d04037b7ec9697/securedrop/source.py#L33) the default Flask request class with a subclassed version that provides anti-forensic protections for file uploads. I would expect `MAX_CONTENT_LENGTH` to still work with the subclass, but it's worth explicitly verifying that expectation.

I can take a stab at implementing this.

**Comment by garrettr** [comment] 2017-05-25 07:42
To clarify the scope of this issue, I first wanted to verify that the file upload limit does indeed *work* in the staging/production environment. I provisioned a staging environment and uploaded a random file that was larger than the limit of 500MB. After a few seconds, I got this response:

<img width="811" alt="screen shot 2017-05-25 at 12 41 24 am" src="https://cloud.githubusercontent.com/assets/407302/26440843/f53404e8-40e2-11e7-9d99-3577c9419c7e.png">

So the file upload limit is clearly working; however, this error message is rather inscrutable. It would be nicer if the error message were more descriptive, and were presented as part of the the Source Interface instead of as a generic error page.

**Comment by garrettr** [comment] 2017-05-31 03:07
Further clarification: unfortunately, there appears to be a discrepancy between Tor Browser's behavior when handling this error on localhost vs. handling it on a `.onion`. When I perform the test from https://github.com/freedomofpress/securedrop/issues/1714#issuecomment-303945909, but use the Source Interface's `.onion` instead of the port forwarded interface (`127.0.0.1:8082`), I get a `The connection was reset` error instead of `Request Entity Too Large`:

<img width="1000" alt="screen shot 2017-05-30 at 8 05 08 pm" src="https://cloud.githubusercontent.com/assets/407302/26614146/7bb5d912-4573-11e7-8c86-11812f1f07b4.png">

**Comment by garrettr** [comment] 2017-06-01 22:29
I probably spent too long investigating this, but it was perversely fascinating. Unfortunately, I think the final outcome should basically be "do nothing," because I could not find any alternatives that I think substantially improve upon the current behavior.

# Background

According to the HTTP 1.1 specification, a web server *should* be able to respond to an oversized request with a `413 Request Entity Too Large` response, which should close the connection while providing a helpful response to the requester. Unfortunately, most web browsers do not implement this correctly. For historical background and a detailed technical explanation, see [Why it is impossible to correctly limit the size of the uploaded file](https://translate.google.com/translate?hl=en&sl=ru&tl=en&u=http://sysoev.ru/web/upload.html), by nginx author Igor Sysoev.

As the title of that blog post suggests, there really is no good way to limit the size of an uploaded file (even though it was written 10 years ago and you would hope the situation would have improved in the interim) without using Javascript, which is an intentional design constraint on the Source Interface.

# Tests

## Test steps

1. Provision a staging environment
2. Access the Source Interface .onion with Tor Browser
3. Create an account
4. Attempt to upload a file that is over the limit

Note that it is important to test using the .onion in Tor Browser - using a different interface, such as the forwarded ports on localhost, or a different browser, can and will give you inconsistent results.

## Test results

### LimitRequestBody in Apache configuration (current implementation)

* "The connection was reset" error appears, quickly (does not require the user to wait for the upload to complete)
* The 413 response page returned by Apache is not displayed

### Flask `MAX_CONTENT_LENGTH`

* "The connection was reset" error appears, but only after a significant delay. It appears the entire file must be uploaded before Flask returns the 413 response, which is an unacceptable user experience.

### StreamConsumingMiddleware

This [Flask snippet](http://flask.pocoo.org/snippets/47/) suggests using a WSGI middleware to avoid the "connection was reset" error, but it still requires transferring all of the bytes to the server before it can return the response. This might be acceptable in some contexts, but it is unacceptable in the context of SecureDrop because the bandwidth of Tor Hidden Services is so limited. A user could wait for literally hours for a large file upload to complete, only to be told that the upload was rejected because it was too large.

## Conclusion

The current behavior has the benefit of failing and thus providing feedback to the user quickly. I'd like to provide a more helpful error message, but I couldn't find a way to return a response without forcing the user to wait for their request to complete, which is an unacceptable user experience in the context of large file uploads over a Tor Hidden Service.

### Options for resolution

1. Do nothing—the current behavior is optimal given the limitations of Tor Browser and the design constraints of the Source Interface.
2. *Additionally* enforce the file upload limit via Flask's `MAX_CONTENT_LENGTH`. We should still use Apache's `LimitRequestBody`, but using `MAX_CONTENT_LENGTH` in addition would have the benefit of enforcing consistent behavior across the development and staging/production environments (albeit via different mechanisms).
    * I am slightly reluctant to implement this because we'd have to do some work with Ansible to make sure the upload limit is consistent across `LimitRequestBody` and `MAX_CONTENT_LENGTH`, and I don't really think it's worth it for a change that only affects the development environment.

@redshiftzero @fowlslegs @conorsch @msheiny Do you guys have any strong opinions about the options I've proposed for resolving this issue?

**Comment by conorsch** [comment] 2017-06-02 22:56
What a bummer. The real clincher is:

> The 413 response page returned by Apache is not displayed

If we could get Apache to return a error response, we wouldn't have to worry about the Flask app code at all. Alas, browsers are finicky creatures, the internet is hard, and we're going to have to let this go. 

Given the limitations we're left with, I vote for the simplest option:

> Do nothing—the current behavior is optimal given the limitations of Tor Browser and the design constraints of the Source Interface.

For those following along at home, #992 is highly relevant to this discussion.

**Comment by garrettr** [comment] 2017-06-05 19:22
Ok, I am going to close this without making any changes. Sadly, I think we are doing the best that we can given the various constraints of SecureDrop, mainly: Tor Browser, and no Javascript on the Source Interface.

**Comment by fowlslegs** [comment] 2017-06-05 19:44
I tried looking back through both the git and Github history, but could not find the reasoning for this setting in the first place. However, if I'm correctly remembering how it was verbally explained to me, the reason is simply that large uploads can take hours to days, and if any of the 7 total nodes along either the client <-> RP circuit or RP <-> server circuit fail during that time the upload will fail.

If we don't have a mechanism that can actually enforce this in an at-all user-friendly way, what's the point of setting such a limit at all? If a big upload happens to work out for someone, why are we receiving the whole thing server-side just to throw it away? I still think we should have a big 'ol upload page warning, but ultimately if we don't have a way to stop it before the upload completes, then then setting `LimitRequestBody` seems only harmful.

**Comment by redshiftzero** [comment] 2017-06-06 02:59
@fowlslegs `LimitRequestBody` does stop the upload before it completes - see @garrettr's [comment](https://github.com/freedomofpress/securedrop/issues/1714#issuecomment-305638371) under "LimitRequestBody in Apache configuration (current implementation)":

> "The connection was reset" error appears, quickly (does not require the user to wait for the upload to complete)

While I hear you on the user unfriendliness, allowing very large uploads is a DoS vector and further exacerbates #986. 

On this issue as a whole, I agree that while the feedback for sources is confusing because they do not get a flashed message, based on @garrettr's analysis we're at the optimal solution there - given that replacing `LimitRequestBody` with `StreamConsumingMiddleware` or `MAX_CONTENT_LENGTH` would be even worse for the user.

However, given the divergent behavior between dev and staging, I think it _does_ make sense to add Flask's `MAX_CONTENT_LENGTH` setting to prevent developer confusion - but only in the `dev` block of `config.py.example`.

**Closed** 2017-06-06 18:35 UTC
Labels: app, bug

**Comment by fowlslegs** [comment] 2017-06-06 21:58
> @fowlslegs LimitRequestBody does stop the upload before it completes - see @garrettr's comment under "LimitRequestBody in Apache configuration (current implementation)":
>> "The connection was reset" error appears, quickly (does not require the user to wait for the upload to complete)

Oh, then I either misunderstood or did not correctly remember details of a convo @garrettr and I had in person. @garrettr, if you could remind me, we were talking about a situation in which a webserver would continue to process and throw out uploads after the limit is reached, in order to get the web browser to finally read the response it had earlier sent. Can you remind me the details/ context of that? Also, you should post that nginx author's blog post because I want to read it and also to just document a good resource on the upload limit issue.

> allowing very large uploads is a DoS vector

I think there are lower-cost, more effective means to DoS a SD instance (e.g., Slowloris). Additionally, if you'll indulge me in a conversation that skirts relevance to the issue at hand, I'm curious how much DoS is really part of our threat model. It currently seems like while some effort is made, there is not an overall plan or threat model.

> further exacerbates #986

I would argue that's kind of hard to say. Setting the upload limit really low (e.g., 10MB, as suggested in that ticket) seems like a good mitigation for the reasons @aliclark lists in their issue. However, 500MB must fall outside the average Tor upload site, and I have to wonder if it's really more of a red flag to upload, say 2GB, versus 500MB. Both could be a video upload, and it seems like it's unlikely one if flagged as suspicious while the other is not. For these reasons I've expressed so far, I continue to believe we should either have a very low upload limit or no upload limit at all.

**Comment by garrettr** [comment] 2017-06-06 22:20
@fowlslegs Most of the answers to your questions are covered in https://github.com/freedomofpress/securedrop/issues/1714#issuecomment-305638371.

I agree that this is hardly a complete solution to prevent DoS of a SecureDrop, but it's a) better than nothing, and b) been around for a while, and we're trying to avoid major behavior changes until we consolidate the development branches with the 0.4 release. As we discussed in yesterday's planning meeting, I think we should revisit DoS mitigation for SecureDrop, but not until after the 0.4 release.

**Comment by fowlslegs** [comment] 2017-06-07 19:03
Thanks.
