### ISSUE TITLE
No source key being generated 1.1.0-rc2

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#4909] opened 2019-10-14 11:06 UTC
## Description

The encryption keys for any source is not being generated. 

Upgraded from 1.0.0 to 1.1.0-rc2 package

## Steps to Reproduce

- [ ] submit a message as a new source
- [ ] Login as a journalist, and flag the new source for generating new key
- [ ] relogin as the source 
- [ ] check the source submission as journalist and still no key has been generated and no way to reply to the source.

## Expected Behavior

The journalist should be able to reply to any new source.

## Actual Behavior

No option to the reply to the source. There is no key generated for the source.

**Comment by emkll** [comment] 2019-10-15 13:56
I could not reproduce the error described above, with cron-apt upgrade from 1.0.0 to 1.1.0 in VMs and the STR provided above. When I submit the file through the source interface, I did not get the "flag for reply" flow.

The upgrade works as expected, and the Journalist can reply to the Source, and I can see the source's private keys in `/var/lib/securedrop/keys` in 1.1.0~rc2.

Are your VMs still available? If so, could you dig up the application server logs?

**Comment by redshiftzero** [comment] 2019-10-15 14:22
two other questions for @kushaldas regarding this scenario:

1. was the source created very shortly after the system booted? 
2. if you leave the VM up for ~10 minutes and create a new source, is this reproducible (i.e. do you still get the flagged for reply flow)?

**Comment by kushaldas** [comment] 2019-10-15 15:29
>1.  was the source created very shortly after the system booted?

No, I created more source to test

>2.if you leave the VM up for ~10 minutes and create a new source, is this reproducible (i.e. do you still get the flagged for reply flow)?

Yes, I am wondering if I should remove that VM in the morning and try again via upgrade path. I have a snapshot of the 1.0.0 release state.

**Comment by redshiftzero** [comment] 2019-10-16 14:48
interesting, that is coming from [the handler](https://github.com/isislovecruft/python-gnupg/blob/master/pretty_bad_protocol/_parsers.py#L995) for the `GenKey` object in python-gnupg - it looks like this is upstream issue https://github.com/isislovecruft/python-gnupg/issues/265

**Comment by redshiftzero** [comment] 2019-10-16 15:43
another step to debug would be to also confirm via inspecting the gpg keyring directly: is the source key not getting created? 

you could try applying this patch https://github.com/isislovecruft/python-gnupg/pull/264/files and see if it resolves (it handles the 'ERROR' key so a `ValueError` doesn't get raised)

**Comment by kushaldas** [comment] 2019-10-16 15:47
Even with that upstream patch I am getting the ValueError. 

```
gnupg                             1.4.20-1ubuntu3.3
```

**Comment by redshiftzero** [comment] 2019-10-16 16:12
hm, since `crypto_util.py` should be using the [`gpg2` binary](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/crypto_util.py#L104) on your system, I expect to see gnupg 2.1 or greater. Since we're no longer testing against gnupg 1.x (as of our removing the trusty test job), it's entirely possible that errors will occur with gnupg 1.x.

**Comment by kushaldas** [comment] 2019-10-17 03:20
Oh yes, gpg2 is also present on the system.

```
gnupg2                            2.1.11-6ubuntu2.1
```

**Comment by kushaldas** [comment] 2019-10-17 10:46
Finally some error log. The following command is causing the error while generating the source keys.

```
['/usr/bin/gpg2', '--no-options', '--no-emit-version', '--no-tty', '--status-fd', '2', '--homedir', '/var/lib/securedrop/keys', '--no-default-keyring', '--keyring', '/var/lib/securedrop/keys/pubring.gpg', '--secret-keyring', '/var/lib/securedrop/keys/secring.gpg', '--pinentry-mode', 'loopback', '--gen-key', '--batch', '--cert-digest-algo', 'SHA512']
gpg: invalid size of lockfile '/var/lib/securedrop/keys/gnupg_spawn_agent_sentinel.lock'
gpg: cannot read lockfile
gpg: can't connect to the agent: Invalid argument
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
```

**Comment by redshiftzero** [comment] 2019-10-17 12:06
interesting.. do you get this same error for other gpg actions? (i assume no and that it's just key generation). what happens if you delete the lockfile?

**Comment by kushaldas** [comment] 2019-10-17 16:23
> interesting.. do you get this same error for other gpg actions?

Only for that one key generation command. I will test in the morning (after the vm restore) what happens when I remove the lock file.

**Comment by redshiftzero** [comment] 2019-10-17 20:41
I tried making an invalid size lockfile (looks like from the gnupg 2.1 source code that a valid size for the lockfile is 11 bytes) and killing gpg-agent, but this did not reproduce the issue: I was still able to generate keys without issue.

**Comment by redshiftzero** [comment] 2019-10-18 19:30
ok this must be an upstream gnupg bug (though I didn't see anything currently filed), specifically with [`assuan`](https://gnupg.org/documentation/manuals/assuan/Introduction.html#Introduction) where the logic handling this lock file is - maybe an error due to interrupted gnupg initialization at some point? e.g. what happens if the writing of the lock file is interrupted?

I'm going to close this for now and we can reopen if we see it again and file upstream if/when we have more info. If any SecureDrop users see this issue, let us know (and as a temporary stopgap you can try to delete the lock).

**Comment by redshiftzero** [comment] 2019-10-29 20:48
I've seen this now for myself in a staging environment when testing something unrelated, reopening.

**Comment by eloquence** [comment] 2019-10-30 16:28
Bumping priority until we have more clarity whether this can arise in prod or not.

**Comment by eloquence** [comment] 2019-10-30 17:05
Next steps:
- Review gnupg lists/tracker for issues that could help identify root cause
- Look at gpg source code to determine when lock is being generated (timebox)

@zenmonkeykstop will investigate today

**Comment by redshiftzero** [comment] 2019-10-30 17:17
btw yesterday I scanned through the bugtracker and the only ticket that I found was https://dev.gnupg.org/T4146 which doesn't seem directly related

**Comment by zenmonkeykstop** [comment] 2019-11-05 17:41
Haven't had any success in reproducing this, or in finding similar cases in bugtracker. Relevant code (checking for lock, not creating it per se) is [here](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=common/asshelp.c;h=f2b4402e161e1ee0f73b6bdded01e46fd4c2099d;hb=e9e5e83ec14459c2fc9060c54fc8e7381b541acd#l318). There is a FIXME note indicating that the dotlock_take() function needs a timeout added, so it's possible there is a race condition here if  multiple copies of gpg_agent are being spawned.

**Comment by eloquence** [comment] 2019-11-06 23:19
For the 11/6-11/20 sprint, we've agreed that @zenmonkeykstop will continue to attempt to get a clean repro (time-box 3-4 hours), and @redshiftzero will help w/ upstream coordination as needed.

**Comment by eloquence** [comment] 2019-11-20 20:23
We've not done formal investigation on this since but we'll consider it as part of QA for 1.2.0. Keeping this on the board for visibility for now.

**Comment by eloquence** [comment] 2019-12-03 20:34
This was part of the test plan for 1.2.0, but we've not been able to reproduce the issue. Closing for now.

**Closed by eloquence** 2019-12-03 20:34 UTC
Labels: QA: Release, needs/reproducing, priority/high
