### ISSUE TITLE
Make SecureDrop's default plaform Debian rather than Ubuntu

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#306] opened 2014-02-19 04:25 UTC
I assume that there's a reason that currently prevents Debian from being the base OS for SecureDrop. We should fix that, and suggest that folks use Debian servers rather than Ubuntu ones.

**Comment by garrettr** [comment] 2015-03-25 23:56
I agree that it might be advantageous to base SecureDrop off of Debian instead of Ubuntu, particularly if that means we can eventually take advantage of the work they are doing on reproducible builds.

In the mean time, Debian Jessie (8.0) is currently frozen and in the RC phase. It's probably best to wait until its released before working on this issue to avoid wasting time/dealing with compat issues to the very old packages in the current stable release.

**Comment by garrettr** [comment] 2015-03-26 22:40
Clarification from @dolanjs on why we chose Ubuntu over Debian in the first place:

> at least a couple years ago, other debian packages didn't ship with default apparmor profiles available, like for ntp, ssh... while ubuntu did. the issue wasn't so much installing apparmor but how many profiles we would need to create and maintain. Have not checked up on it in a long time so not sure current state of apparmor profiles in debian

**Comment by fowlslegs** [comment] 2017-06-20 16:35
Going to close this issue because the arguments for switching to Debian are strongly outweighed by the huge additional burden this would put on existing admins (not to mention developers) to make the switch. Upgrading to Ubuntu 16.04 is much more practical and less time consuming.

**Closed by fowlslegs** 2017-06-20 16:35 UTC
