### ISSUE TITLE
Codenames with spaces at the end are still valid.

### ISSUE THREAD

**Issue by EdOverflow** [freedomofpress/securedrop#3213] opened 2018-04-01 13:58 UTC
# Bug

## Description

On `:8080/login` when submitting a valid codename with extra spaces the user is still logged in.

## Steps to Reproduce

1. Visit `:8080/login`;

![image](https://user-images.githubusercontent.com/18099289/38173930-c1dd4e82-35c5-11e8-9d3c-3c2ade9905d9.png)

2. Submit a valid codename, but add a couple spaces after the string; i.e. `word word word word word word word[SPACE][SPACE][SPACE]`.

## Expected Behavior

SecureDrop should reject the codename as it does not match the user's generated codename.
 
## Actual Behavior

User is logged in.

**Comment by dachary** [comment] 2018-04-01 13:59
I was able to reproduce the problem by:

* creating a journalist with name "withtralingspace " (note the trailingspace) via the admin interface
* being unable to login because the trailing space is ignored / trimmed in the login page

**Comment by dachary** [comment] 2018-04-01 14:02
@EdOverflow it does not matter that the source interface trims trailing spaces because the source code name is auto-generated and will never end with a space so there is no risk of confusion.

**Comment by heartsucker** [comment] 2018-04-02 14:12
We actually have test cases to ensure that this behavior is explicitly allowed (see `test_source.py::test_login_with_whitespace`). I'm closing this as not a bug.

**Closed by heartsucker** 2018-04-02 14:12 UTC
Labels: app, goals: journalist experience

**Comment by dachary** [comment] 2018-04-02 14:20
> We actually have test cases to ensure that this behavior is explicitly allowed

For sources yes, but what about journalists?

**Comment by heartsucker** [comment] 2018-04-02 14:32
If we want to discuss that, that would be a separate issue. I'm not sure about that behavior offhand.

**Comment by dachary** [comment] 2018-04-02 14:57
https://github.com/freedomofpress/securedrop/issues/3216
