### ISSUE TITLE
Terminology used in docs is confusing

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1138] opened 2015-10-14 17:19 UTC
It took me a while to become accustomed to the specific meaning of “SecureDrop Application Key”, “Secure Viewing Station”, “Journalist Workstation” and so on. Perhaps there are better names which can more-immediately indicate their function and role?

**Comment by conorsch** [comment] 2015-10-14 17:35
"Secure Viewing Station" and "Journalist Workstation" should be left as-is, although explicated at length in the Terminology Guide. The names should *not* be abbreviated in the docs, as discussed in #1137.

As for "SecureDrop Application Key", that's rather ambiguous. The term refers to the GPG key used to encrypt submissions through SecureDrop. The public key lives on the Application Server (also inside the Admin Workstation persistence volume, from where it is provisioned), and the private key lives on the Secure Viewing Station, also inside persistence. How about the following alternatives:

1. "SecureDrop Primary Encryption Key"
2. "SecureDrop Encryption Key"
3. "SecureDrop Application GPG Key"

Listed there in order of my preference.

**Comment by conorsch** [comment] 2015-11-07 18:28
We've added mention of style for the docs to the [Contributor Guidelines](https://docs.securedrop.org/en/latest/development/documentation.html#style-guide), and the [Terminology Guide](https://docs.securedrop.org/en/latest/terminology.html) has gotten a bit of attention, too.

Leaving this issue open since I haven't gone through the rewritten docs and confirmed that we've normalized all the occurrences of the terminology. Once that's done, ready to close. Holler if you have more thoughts on disambiguation, @flamsmark.

**Comment by fowlslegs** [comment] 2016-11-05 23:41
Relevant: https://github.com/freedomofpress/securedrop/pull/1395.

**Comment by freddymartinez9** [comment] 2016-11-06 19:53
I think from a usability standpoint we should use "SecureDrop Submission Key". "SecureDrop Encryption Key" is a bit vague and misleading. There are multiple encryption keys thought the SD infrastructure (the tails admin drive has one, the keypass database has a separate one etc). I think "Primary Encryption Key" has similar problems, I think _primary_ is a bit vague, what does primary mean in this context?  I'll open a PR.

**Comment by redshiftzero** [comment] 2016-12-07 21:07
Looks like this was addressed in #1395 and #1461, so closing for now.

**Closed by redshiftzero** 2016-12-07 21:07 UTC
Labels: docs, hackathon, Pending PR
