### ISSUE TITLE
Old SecureDrop logos in clean install of 1.0.0-rc2

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#4788] opened 2019-09-10 21:03 UTC
## Description

On a clean install of SecureDrop 1.0.0-rc2, the old logo is visible in the Source and Journalist interfaces and desktop icons, despite the new colour scheme.

## Steps to Reproduce

- Clean install of Ubuntu on app and mon
- Fresh clone of SecureDrop on admin-ws, `config` and `install` of 1.0.0-rc2
- Run `tailsconfig` and/or browse to Source or Journalist interface and observe old SD desktop icons

## Expected Behavior

New SecureDrop desktop shortcut and logo in Source and Journalist Interfaces to match colour scheme

## Actual Behavior
Desktop icons display old logo, Source and Journo interfaces display old logo (but new favicon and font colour).

Screenshots:

![journo_if](https://user-images.githubusercontent.com/22777700/64649908-6e32d800-d40d-11e9-98ed-9d2b9a3659f6.png)
![login](https://user-images.githubusercontent.com/22777700/64649909-6e32d800-d40d-11e9-8614-05e0902c802c.png)
![old_new_logos](https://user-images.githubusercontent.com/22777700/64649910-6e32d800-d40d-11e9-9870-488543542903.png)

## Comments

If relevant, I did not provision the admin-ws from scratch, but I did delete the `~/Persistent/securedrop` directory and re-clone the repo as part of this install.

**Comment by redshiftzero** [comment] 2019-09-10 21:08
thanks for the clear report @rocodes, this is an issue in 1.0.0-rc2 that was fixed by #4754 (duplicate of #4753)

we haven't made a new rc since the issue was fixed but probably should do so tomorrow since a bunch of fixes have been merged cc @kushaldas

**Comment by eloquence** [comment] 2019-09-13 06:58
While the issue of the instance logo was a build-only issue, the following logos still need to be updated to the new version:

- Updater UI: `journalist_gui/journalist_gui/static/securedrop_icon.png`
- Desktop shortcuts: `install_files/ansible-base/roles/tails-config/files/securedrop_icon.png`

I'll target a PR for that tomorrow in case we may be able to include it in a final RC on Monday.

**Closed** 2019-09-13 23:56 UTC
Labels: QA: Release
